### ISSUE TITLE
buildpack doesn't compile source code during staging

### ISSUE THREAD

**Issue by sesmith177** [cloudfoundry/dotnet-core-buildpack#105]
When reviewing the buildpack, we noticed that if app source code is pushed (i.e. not an already published app), it is not compiled during staging. Instead, it is compiled in the runtime container with `dotnet run`

We are currently working on a PR to change this behavior so that the app is compiled in the staging container. Still, we would like to discuss whether we are missing some reason (technical or otherwise) why the current behavior (compiling in the runtime container) would be preferable.

Thanks,
Sam

**Comment by opiethehokie** [comment]
@sesmith177 I don't recall a reason for the current behavior being preferable, it's probably more like leaving it to `dotnet run` (or previously some `dnu` command) to handle compilation simplified things early on when the CLI was changing between beta releases

**Comment by degrim** [comment]
@opiethehokie @sesmith177 `dotnet run` was the direct replacement for `dnx web` from the earlier CLI betas.  This could be replaced with `dotnet build` now and the command to start the application would just be `dotnet path/to/application_name.dll` then.  If we're going to do that, we should add the ability to pass different command-line options to the `dotnet build` command as well (`--no-incremental`, `--configuration`, etc).

**Comment by sesmith177** [comment]
Thanks.

Right now we're going with `dotnet publish` with a default configuration of `Release`. It will probably be a separate track of work to add the ability to configure command line options

**Comment by degrim** [comment]
@sesmith177 `dotnet publish` instead of `dotnet build` would be a breaking change.  `dotnet run` calls `dotnet build`, not `dotnet publish`.  Users will need to modify their `project.json`'s `publishOptions` section to be similar to the `buildOptions` section to continue using the buildpack if the command is changed to `dotnet publish`.

**Comment by sesmith177** [comment]
It looks like there would be breaking changes either way. Specifically, the packages in the .nuget cache are in different locations in the staging container vs. the runtime container.

So in order for the packages to be found at runtime, the following key needs to be added to project.json:
  
 ```  "runtimeOptions": {
    "additionalProbingPaths": [
      "/app/.nuget/packages"
    ]
  }
```

As such, we're going to hold off on this change until the tooling moves to using `.csproj` / `msbuild` and make the breaking change then.

**Comment by sesmith177** [comment]
We've merged: https://github.com/cloudfoundry/dotnet-core-buildpack/pull/132 to develop so msbuild apps are now published during staging.
