### ISSUE TITLE
Ending .Net Core buildpack CF incubation period

### ISSUE THREAD

**Issue by sclevine** [cloudfoundry/dotnet-core-buildpack#110]
Hi .Net Core CF Buildpack team,

We would like to formally end the incubation period and move this buildpack from the "cloudfoundry-incubator" Github org to the "cloudfoundry" Github org. All existing redirects will be preserved.

Are there any objections to this? If not, we will instruct the org administrators to move the repo ASAP.

Thanks!

**Comment by sclevine** [comment]
@degrim @opiethehokie is this okay?

**Comment by degrim** [comment]
@sclevine That sounds fine

**Comment by opiethehokie** [comment]
@sclevine sounds good to me too

**Comment by sclevine** [comment]
Thanks, done!
