### ISSUE TITLE
How was the libunwind included in the buildpack constructed?

### ISSUE THREAD

**Issue by RochesterinNYC** [cloudfoundry/dotnet-core-buildpack#114]
The buildpack currently uses the libunwind hosted on github that was uploaded with a past release: https://github.com/cloudfoundry/dotnet-core-buildpack/blob/master/manifest.yml#L28

Where does this binary come from and how was it constructed?

**Comment by degrim** [comment]
It was built with the Dockerfile in the buildpack root:
https://github.com/cloudfoundry/dotnet-core-buildpack/blob/master/Dockerfile.libunwind

**Comment by RochesterinNYC** [comment]
This is related to the following story: https://www.pivotaltracker.com/story/show/132852595

**Comment by RochesterinNYC** [comment]
Gotcha, thanks. We've compiled `libunwind` using the method listed in the `Dockerfile.libunwind` file. However, the end artifact binary files are different. We suspect this is because the GCC version on the latest version of the rootfs is different from the version at the time `libunwind` was initially compiled.

We're going to recompile using the latest version of the rootfs and upload those binary files to the `buildpacks.cloudfoundry.org` bucket and use that in the buildpack. How does that sound?

We're doing this manually rather than building out automation for this as `libunwind` very rarely seems to receive updates.

**Comment by degrim** [comment]
@RochesterinNYC Sounds good to me.

**Comment by jchesterpivotal** [comment]
We've built and uploaded a copy to the general buildpacks bucket, so I'm closing this one. Thanks @degrim!
