### ISSUE TITLE
Add error if .deployment found but path is not valid

### ISSUE THREAD

**Issue by miclip** [cloudfoundry/dotnet-core-buildpack#115]
Would it be possible to throw a meaningful error if it finds a .deployment file but the path is not valid? 

I spent a long time trying to understand why my deployment was failing, the error "_Multiple paths contain a project.json file, but no .deployment file was used_" could mean it couldn't find the file or the path is invalid. I'd provided a path of "./src/Project" rather than "src/Project" .

`fail 'Deployment found a .deployment file however the path specified was invalid.' if paths.include?(path) `

**Comment by RochesterinNYC** [comment]
@miclip Thanks for the issue. We've created a story to tighten the `.deployment` contract (which would include both a better error message for your case and proper handling of `.` in paths here: https://www.pivotaltracker.com/story/show/133932443

@cloudfoundry/ibm-buildpacks Any thoughts on these changes to the `.deployment` contract?

**Comment by degrim** [comment]
It looks like we need to normalize the paths in the [deployment_file_project method](https://github.com/cloudfoundry/dotnet-core-buildpack/blob/master/lib/buildpack/app_dir.rb#L55) in the same way that we do in the [with_project_json method](https://github.com/cloudfoundry/dotnet-core-buildpack/blob/master/lib/buildpack/app_dir.rb#L35).  That should clear up the issue of not detecting paths which begin with "./", but we still would need to add some more intuitive error messages when the path specified does not exist.

**Comment by miclip** [comment]
Awesome, both solutions would be great. It was confusing as I couldn't tell if the .deployment file was being dropped. Thanks.

**Comment by RochesterinNYC** [comment]
The functionality for more intuitive error messages when the specified path does not exist has been done with https://github.com/cloudfoundry/dotnet-core-buildpack/commit/84d312aea3bcf1dbec21a0e88573ecdde6378310

The work to normalize the paths is prioritized here: https://www.pivotaltracker.com/story/show/133851173

**Comment by keaty** [comment]
The ability to specify paths that include `./` has been added with https://github.com/cloudfoundry/dotnet-core-buildpack/commit/ededf6e2d224a703ee29479cc32244b838dba218
