### ISSUE TITLE
Error deploying with wildcard platform version

### ISSUE THREAD

**Issue by jmcarp** [cloudfoundry/dotnet-core-buildpack#116]
The fixture dotnet app in the cf acceptance tests specifies a wildcard for the platform version: https://github.com/cloudfoundry/cf-acceptance-tests/blob/master/assets/dotnet-core/project.json#L8-L11. It looks like dotnet apps with wildcard platform versions fail to deploy on the current buildpack with the following:

```
2016-11-18T10:58:55.77-0500 [APP/PROC/WEB/0]ERR The specified framework 'Microsoft.NETCore.App', version '1.1.0' was not found.
2016-11-18T10:58:55.77-0500 [APP/PROC/WEB/0]ERR   - Check application dependencies and target a framework version installed at:
2016-11-18T10:58:55.77-0500 [APP/PROC/WEB/0]ERR       /home/vcap/app/.dotnet/shared/Microsoft.NETCore.App
2016-11-18T10:58:55.77-0500 [APP/PROC/WEB/0]ERR   - The following versions are installed:
2016-11-18T10:58:55.77-0500 [APP/PROC/WEB/0]ERR       1.0.0
2016-11-18T10:58:55.77-0500 [APP/PROC/WEB/0]ERR   - Alternatively, install the framework version '1.1.0'.
```

I'm not sure if this is an issue with the buildpack or the fixture app in the acceptance tests (or maybe our configuration is off somehow), but either way, we're looking at a failing test. Should dotnet core apps deploy with a wildcard platform version?

**Comment by degrim** [comment]
Using a wildcard in your project.json will grab the latest package version from nuget.org, that version is 1.1.0 right now which is not included in the latest buildpack release.  The buildpack defaults to a specific version if your app does not specify a version in the global.json file.
Your app should specify a version at https://github.com/cloudfoundry/cf-acceptance-tests/blob/master/assets/dotnet-core/project.json#L10 as well as adding a global.json file at the solution-level specifying the CLI version to be installed (which also has to be a version that the buildpack supports).

Example project.json file:

    {
      "buildOptions": {
        "emitEntryPoint": true,
        "debugType": "portable"
      },
      "dependencies" : {
        "Microsoft.AspNetCore.Server.Kestrel": "1.0.1",
        "Microsoft.NETCore.App": {
          "type": "platform",
          "version": "1.0.1"
        },
        "Microsoft.Extensions.Configuration.CommandLine": "1.0.0"
      },
      "frameworks": {
        "netcoreapp1.0": { }
      }
    }

Example global.json file if the Microsoft.NETCore.App version is specifed as "1.0.1":

    {
        "projects": [ "src" ],
        "sdk": {
            "version": "1.0.0-preview2-003131"
        }
    }

**Comment by jmcarp** [comment]
Thanks! It's not my app, but I'll send a patch to cf-acceptance-tests.

**Comment by degrim** [comment]
cloudfoundry/cf-acceptance-tests#152 should resolve this by using a vendored app.

**Comment by RochesterinNYC** [comment]
We're closing this issue as we've already submitted the PR @degrim mentioned above to fix this issue. Thanks!

**Comment by jmcarp** [comment]
Thanks for the fix!
