### ISSUE TITLE
Buildpack doesn't support .NET Core 1.1.0 (1.0.0-preview2-1-003177)

### ISSUE THREAD

**Issue by mschnack** [cloudfoundry/dotnet-core-buildpack#117]

**Comment by degrim** [comment]
@mschnack Support has already been added in the `develop` branch and will be merged to master when the next release is created.

**Comment by degrim** [comment]
@mschnack You can also use .NET Core 1.1.0 with the current release by publishing your app as a self-contained application and pushing from the output folder of the `dotnet publish` command.

**Comment by mschnack** [comment]
Thank you, @degrim. Will keep checking to see when the release is created :)

**Comment by degrim** [comment]
@mschnack The release (1.0.6) has been created now, so closing this issue.
