### ISSUE TITLE
We should not rely on global.json to specify framework version

### ISSUE THREAD

**Issue by degrim** [cloudfoundry/dotnet-core-buildpack#120]
Currently, we rely on the SDK version to determine which framework version gets installed by the buildpack because the SDKs come packaged with a specific framework version.  We are only packaging SDKs with the buildpack currently, but I am proposing that we include the runtime binaries with the buildpack as well.
  This change would allow us to install only the latest SDK and detect which framework version(s) need to be installed after the `dotnet restore` command is executed by reading the directory names under the `~/.nuget/packages/Microsoft.NETCore.App/` directory.  In the case of portable applications, we can still use the current method of reading the runtimeconfig.json files to determine the framework version.  This change would also reduce the size of the resulting droplet for portable applications, and allow the use of compiler tools which require a different runtime version than the application itself (ex: F# and VB compiler packages).
  In cases where no global.json version is specified, we would want to install the latest SDK + latest LTS framework.

@sclevine @sesmith177 This issue is a continuation of our discussion on Slack last week.
/cc @opiethehokie @RochesterinNYC @flavorjones

**Comment by sesmith177** [comment]
@degrim We've actually been working on this; the commit on develop is: 37502ffbe4ae699f03b4a2d29b55c344b3beb782 

One thing we found while implementing this is that a default framework version doesn't really make sense as we would only fall back to that in the case that there are no frameworks under `~/.nuget/packages/Microsoft.NETCore.App`

We've left the default SDK as `1.0.0-preview2-003131` but I don't see an immediate issue with bumping to `1.0.0-preview2-1-003177`

**Comment by degrim** [comment]
@sesmith177 We can only bump the default SDK to `1.0.0-preview2-1-003177` once the work is completed to provide the frameworks separately.  Otherwise, we'd be promoting the Current framework over the LTS framework.

**Comment by degrim** [comment]
Closing this issue since the changes have already been made in `develop` to separate frameworks and sdks.
