### ISSUE TITLE
how to compile release/debug mode

### ISSUE THREAD

**Issue by emailtowalter** [cloudfoundry/dotnet-core-buildpack#124]
Hi... dotnet build command has a -c parameter to specific release vs debug mode.  I wonder how to control this using buildpack? 

sorry for asking the obvious question. Cannot find any documentation. 

Thanks

**Comment by degrim** [comment]
@emailtowalter Currently there is no way to control that in the buildpack.  If you are intending to build a Release build, I would recommend publishing the application locally and deploying the published files instead of the source code.  I've noticed slightly better performance when using published files vs compiling and running from source.

**Comment by emailtowalter** [comment]
Thanks for the quick reply. Any future plan to support‎ it?Walter                                                                                                                                                                                                                                                                                                                                        Sent from my BlackBerry 10 smartphone on the Rogers network.                                                                                                                                                                                                                From: Daniel GrimSent: Friday, December 9, 2016 10:59 AMTo: cloudfoundry/dotnet-core-buildpackReply To: cloudfoundry/dotnet-core-buildpackCc: emailtowalter; MentionSubject: Re: [cloudfoundry/dotnet-core-buildpack] how to compile release/debug mode (#124)@emailtowalter Currently there is no way to control that in the buildpack.  If you are intending to build a Release build, I would recommend publishing the application locally and deploying the published files instead of the source code.  I've noticed slightly better performance when using published files vs compiling and running from source.

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/cloudfoundry/dotnet-core-buildpack","title":"cloudfoundry/dotnet-core-buildpack","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/cloudfoundry/dotnet-core-buildpack"}},"updates":{"snippets":[{"icon":"PERSON","message":"@degrim in #124: @emailtowalter Currently there is no way to control that in the buildpack.  If you are intending to build a Release build, I would recommend publishing the application locally and deploying the published files instead of the source code.  I've noticed slightly better performance when using published files vs compiling and running from source."}],"action":{"name":"View Issue","url":"https://github.com/cloudfoundry/dotnet-core-buildpack/issues/124#issuecomment-266049197"}}}

**Comment by degrim** [comment]
@emailtowalter Once the changes are made to publish the application during the staging process I think that would be a good time to look at including support for this.
@sesmith177 any thoughts?

**Comment by sesmith177** [comment]
@emailtowalter @degrim I agree. In the 'dotnet publish' work we've done we defaulted to passing `-c Release ` to `dotnet publish`. I don't see a reason we couldn't allow this to be configured

**Comment by RochesterinNYC** [comment]
For context, the work for that functionality (compiling during staging instead of at runtime) is on this branch: https://github.com/cloudfoundry/dotnet-core-buildpack/tree/compile-app-in-staging

**Comment by sesmith177** [comment]
Current work in progress on branch: https://github.com/cloudfoundry/dotnet-core-buildpack/tree/publish-msbuild

**Comment by sesmith177** [comment]
@emailtowalter The work implementing is now on the `develop` branch and should be in the next release. The implementation is as follows:

- By default an msbuild app will be published using the Debug configuration
- If your application manifest includes the environment variable `PUBLISH_RELEASE_CONFIG: true` it will be published using the Release configuration.

This matches the default behavior of the CLI.
