### ISSUE TITLE
ASP.NET Core Bluemix sample+VS 2015 update 3

### ISSUE THREAD

**Issue by swathi25gs** [cloudfoundry/dotnet-core-buildpack#127]
Hi,
I created a ASP.NET Core cloud foundry apps in IBM bluemix, which works fine. But when i download and try to build in VS 2015 update 3, i am not able to restore the packages hence getting the following error:

**PATH=.\node_modules\.bin;C:\Program Files (x86)\Microsoft Visual Studio 14.0\Web\External;%PATH%;C:\Program Files (x86)\Microsoft Visual Studio 14.0\Web\External\git
C:\Program Files\dotnet\dotnet.exe restore "C:\Users\c8\Downloads\HelloWorld(1)\.vs\restore.dg"
log  : Restoring packages for C:\Users\c8\Downloads\HelloWorld(1)\src\dotnetstarter\project.json...
error: Unable to resolve 'Microsoft.Extensions.Configuration.CommandLine (>= 1.0.0)' for '.NETCoreApp,Version=v1.0'.
log  : Writing lock file to disk. Path: C:\Users\c8\Downloads\HelloWorld(1)\src\dotnetstarter\project.lock.json
Errors in C:\Users\c836774\Downloads\HelloWorld(1)\src\dotnetstarter\dotnetstarter.xproj
    Unable to resolve 'Microsoft.Extensions.Configuration.CommandLine (>= 1.0.0)' for '.NETCoreApp,Version=v1.0'.
log  : C:\Users\c8\Downloads\HelloWorld (1)\src\dotnetstarter\dotnetstarter.xproj
log  : Restore failed in 966ms.**

Could you please help me

**Comment by degrim** [comment]
@swathi25gs The issue only occurs when running locally, not when using the buildpack?
If you've installed VS2017 RC, that may be causing issues if you don't have the latest VS2015 tools update installed (download [here](https://go.microsoft.com/fwlink/?LinkId=827546)).

**Comment by swathi25gs** [comment]
@degrim , I downloaded the package from ibm bluemix and when trying to build locally i am unable to restore the packages mentioned in the error message.  I have upgraded the tool set of VS 21015 as mentioned by you & i dont have VS 2017 either

**Comment by swathi25gs** [comment]
I was able to resolve this by making changes to nuget.config to :+1: <?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageSources>
    
    <clear />
    <add key="dotnet-core" value="https://dotnet.myget.org/F/dotnet-core/api/v3/index.json" />
    <add key="api.nuget.org" value="https://api.nuget.org/v3/index.json" />
  </packageSources>
</configuration>
