### ISSUE TITLE
STDOUT is not displaying on cf console

### ISSUE THREAD

**Issue by ishwar1987** [cloudfoundry/dotnet-core-buildpack#129]
HI,
I am pushing the sample .net application using following command.
cf push log4net4 -s windows2012R2 -b https://github.com/cloudfoundry/dotnet-core-buildpack.git

I wrote the following lines into the my application but its not printing on cf console(cf cli).
Console.WriteLine("user has click on button..console");

Does that support writing logs to a STDOUT  format ?

Even after pushing successfully, I am not able to do cf ssh log4net5.
its giving me an error.
Error: SSH session allocation failed: ssh: rejected: administratively prohibited (SSH is not supported on windows cells)
But according to my knowledge it should have worked as it is runnning on linux stack.

**Comment by flavorjones** [comment]
Hello! Thanks for asking these questions. There's a few things to unpack in your question ...

1. You're pushing to a Windows stack, not a Linux stack. This is indicated by the `-s windows2012R2` commandline option.
2. the `dotnet-core buildpack` is a Linux buildpack; it will not work for native Windows applications running on the `windows2012r2` stack. In fact, the `windows2012r2` stack does not, as of this writing, support buildpacks at all (though this is on the near-term roadmap).
3. You're likely successfully uploading your files into a droplet; but my guess is that the application is not starting up. What's the output from `cf apps` or `cf app log4net4`?
4. `cf ssh` is not, as of this writing, supported on the `windows2012r2` stack; though there is work-in-progress on [this side branch](https://github.com/cloudfoundry/diego-ssh/compare/master...greenhouse-org:windows-ssh).

Does all this make sense?

**Comment by ishwar1987** [comment]
HI,
1)Using the following command:

cf push log4net5 -s windows2012R2 -b https://github.com/cloudfoundry/dotnet-core-buildpack.git
its push and its running but when  I am printing output on STDOUT
in  .net application(console.writeln()),its not displaying in cf console nor  in loggregator. 

any idea ?

2)while pushing the app using the following commands
cf push log4net4 -b  https://github.com/cloudfoundry/dotnet-core-buildpack.git  

I am getting the following error:

112 package(s) to /tmp/rdkmropw.uwe/rdkmropw.uwe.csproj
       /tmp/app/WebApplication3.csproj(144,3): error MSB4019: The imported project "/tmp/app/.dotnet/sdk/1.0.0-preview3-004056/Extensions/Microsoft/VisualStudio/v10.0/WebApplications/Microsoft.WebApplication.targets" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.
       FAILED: command failed, exit status 1
       FAILED: Restoring dependencies with Dotnet CLI failed, command failed, exit status 1
Failed to compile droplet
Exit status 223
Staging failed: Exited with status 223
Destroying container
Successfully destroyed container

FAILED
Error restarting application: BuildpackCompileFailed

**Comment by sesmith177** [comment]
@ishwar1987 As @flavorjones commented, this buildpack is only supported on the Linux stack. 

Regarding the app that is failing to stage (when you run `cf push log4net5 -b https://github.com/cloudfoundry/dotnet-core-buildpack.git`), we need more information to determine why it is not staging. Could we see the `.csproj` file for this project?

**Comment by sesmith177** [comment]
@ishwar1987 we still need more information to determine why your app isn't staging. Could we see the `.csproj` file for this project?

**Comment by ishwar1987** [comment]
yes .csproj file is exist. I have attached the contain of that file.

[WeApplicaiton3csproj.txt](https://github.com/cloudfoundry/dotnet-core-buildpack/files/699134/WeApplicaiton3csproj.txt)

**Comment by degrim** [comment]
@ishwar1987 That csproj file is for a .NET Framework project, which this buildpack does not support.  This buildpack only supports .NET Core.

**Comment by dgodd** [comment]
@ishwar1987 Do you have any more questions?

**Comment by sesmith177** [comment]
@ishwar1987 We are closing this since this buildpack is not involved when pushing to the windows stack and this buildpack does not support .NET Framework projects (only .NET core)
