### ISSUE TITLE
NOTICE: Breaking change in the buildpack msbuild alpha tooling

### ISSUE THREAD

**Issue by sclevine** [cloudfoundry/dotnet-core-buildpack#130]
The v1.0.7 release of the .NET Core buildpack added support for msbuild tooling as an alternative to project.json tooling. This tooling is not GA, and we do not yet recommend using it in production. The first release of the buildpack after January 22, 2017 will build all apps that use the msbuild tooling using `dotnet publish` during staging. This will dramatically reduce the droplet size for msbuild apps, but it may require making configuration changes to these apps to prevent them from breaking. The behavior for apps that used the project.json tooling will remain unchanged for the foreseeable future to avoid breaking production apps.

To migrate your msbuild apps to the new staging process, you may need to add configuration to your csproj files in order to copy files that are required for your project. For example:
```
  <ItemGroup>
    ...
    <Content Include="appsettings.json">
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
    </Content>
  </ItemGroup>
```

**Comment by sesmith177** [comment]
If compiling/publishing your app dynamically creates/generates files, you may need to add configuration to your csproj to copy the dynamically generated files to the publish directory. For example:

```
  <Target Name="CustomCollectFiles" DependsOnTargets="*STEP_GENERATING_FILES*">
    <ItemGroup>
      <Content Include="*GLOB_MATCHING_FILES*">
        <CopyToPublishDirectory>Always</CopyToPublishDirectory>
      </Content>
    </ItemGroup>
  </Target>
  <PropertyGroup>
    <AssignTargetPathsDependsOn>
      CustomCollectFiles;
      $(AssignTargetPathsDependsOn);
    </AssignTargetPathsDependsOn>
  </PropertyGroup>

```
