### ISSUE TITLE
Unable to restage

### ISSUE THREAD

**Issue by swathi25gs** [cloudfoundry/dotnet-core-buildpack#131]
Hi,
I am unable to restage my ASP.NET core cloudant web starter after adding /removing services. I get this error any one else faced this issue:
{ code: 'ESOCKETTIMEDOUT', connect: false, name: 'Error', message: 'ESOCKETTIMEDOUT', stack: 'Error: ESOCKETTIMEDOUT\n at ClientRequest. (/home/vcap/app/node_modules/request/request.js:778:19)\n at ClientRequest.g (events.js:291:16)\n at emitNone (events.js:86:13)\n at ClientRequest.emit (events.js:185:7)\n at TLSSocket.emitTimeout (_http_client.js:620:10)\n at TLSSocket.g (events.js:291:16)\n at emitNone (events.js:86:13)\n at TLSSocket.emit (events.js:185:7)\n at TLSSocket.Socket._onTimeout (net.js:339:8)\n at ontimeout (timers.js:365:14)\n at tryOnTimeout (timers.js:237:5)\n at Timer.listOnTimeout (timers.js:207:5)' }

**Comment by degrim** [comment]
@swathi25gs This seems like an error coming from some node package that you're using.  Are you running something from the pre/postcompile scripts section?

**Comment by sesmith177** [comment]
@swathi25gs thoughts regarding @degrim's comment?

**Comment by sesmith177** [comment]
@swathi25gs thoughts regarding the above comments?

**Comment by dgodd** [comment]
@swathi25gs thoughts regarding the above comments?

**Comment by sesmith177** [comment]
@swathi25gs Since we have not heard a response and are unclear on what your issue was, we will be closing this issue.
