### ISSUE TITLE
Adding support for AppDynamics monitoring

### ISSUE THREAD

**Issue by nkatre** [cloudfoundry/dotnet-core-buildpack#133]
Is there a way we can monitor .NET core apps deployed in PCF using AppDynamics monitoring solution

**Comment by degrim** [comment]
@nkatre According to the [AppDynamics website](https://docs.appdynamics.com/display/PRO42/.NET+Supported+Environments), .NET Core 1.0 and 1.1 are not currently supported by AppDynamics.  As this buildpack only supports .NET Core 1.0 and 1.1, we cannot add support for this yet.

**Comment by sesmith177** [comment]
@nkatre we will close this one for now. Please create a new issue once AppDynamics supports .NET Core.
