### ISSUE TITLE
Buildpack installs deprecated runtime versions when a newer patch version is already installed

### ISSUE THREAD

**Issue by degrim** [cloudfoundry/dotnet-core-buildpack#147]
What version of the buildpack you are using?
v1.0.18

If you were attempting to accomplish a task, what was it you were attempting to do?
Using the BundlerMinifier.Core tool which provides the `dotnet bundle` command for use in post-publish scripts.

What did you expect to happen?
The latest version of BundlerMinifier.Core requires Microsoft.NETCore.App >= 1.1.0.  As version 1.1.2 was already installed with the 1.0.4 SDK, I expect that no additional runtimes should be required to be installed because the 1.1.2 runtime will satisfy this dependency for the tool.

What was the actual behavior?
The deprecated runtime version 1.1.0 was installed, despite version 1.1.2 already being installed.  This will cause a staging failure once version 1.1.0 is removed from the buildpack.

I think that we should be able to modify the frameworks installer to only install an additional version if there is not already a higher patch version for the same major/minor version already installed.

For example:

If runtime version 1.1.2 is already installed and a package requires version >= 1.1.0, no additional versions will be installed.
If version 1.1.2 is installed and a package requires version >= 1.1.3, version 1.1.3 should be installed.
If the csproj file specifies a runtime version using the `RuntimeFrameworkVersion` element, that exact version should be installed if it is not already installed.

@sesmith177 @sclevine any thoughts?

**Comment by sesmith177** [comment]
So from (list of versions required by `dotnet restore` - installed versions) we would only install those that either
- do not have a higher patch version already installed
- are exactly the version specified by `RuntimeFrameworkVersion` if it exists

Assuming that's the case, are there packages that e.g. require  `<= 1.1.1`? and would fail if both `1.1.1` and `1.1.2` were not installed?

**Comment by degrim** [comment]
Package references are always `>=` the version specified, according to Microsoft's [documentation](https://docs.microsoft.com/en-us/nuget/consume-packages/package-references-in-project-files) on package references in project files.

**Comment by sesmith177** [comment]
@degrim sounds good; we will begin working on this today

**Comment by sesmith177** [comment]
@degrim do you have a sample app that reproduces the problem? We tried pushing a simple app with BundlerMinifier.core and 1.1.0 was not installed:

```
         Installing BundlerMinifier.Core 2.4.337.
         Generating MSBuild file /tmp/app/obj/with_bundler_minifier.csproj.nuget.g.props.
         Generating MSBuild file /tmp/app/obj/with_bundler_minifier.csproj.nuget.g.targets.
         Writing lock file to disk. Path: /tmp/app/obj/project.assets.json
         Restore completed in 1.68 sec for /tmp/app/with_bundler_minifier.csproj.

         NuGet Config files used:
             /tmp/app/.nuget/NuGet/NuGet.Config

         Feeds used:
             https://api.nuget.org/v3/index.json

         Installed:
             2 package(s) to /tmp/app/with_bundler_minifier.csproj
       OK
       Detected .NET Core runtime version(s) 1.0.5, 1.1.2 required according to 'dotnet restore'
-----> Installing required .NET Core runtime(s)
       .NET Core runtime 1.0.5 already installed
       .NET Core runtime 1.1.2 already installed
       OK
```

**Comment by degrim** [comment]
@sesmith177 https://github.com/IBM-Bluemix/aspnet-core-helloworld/tree/develop

**Comment by sesmith177** [comment]
PR here: https://github.com/cloudfoundry/dotnet-core-buildpack/pull/149
