### ISSUE TITLE
ASP.Net Core Web API  deployed on Linux cell with dotnet-core-buildpack gives 502 error

### ISSUE THREAD

**Issue by abhijitpatil1009** [cloudfoundry/dotnet-core-buildpack#148]
Hi ,
 I am trying to deploy ASP.Net CORE Web API on PCF environment with dotnet_core_buildpack on linux cell getiing 502 error please guide me how i can route to defualt route or how i can route to index.html page in wroot folder.

What version of Cloud Foundry and CF CLI are you using? (i.e. What is the output of running `cf curl /v2/info && cf version`?

Cloud Foundry Version
C:\SampleASP.Net\CoreWebAPI\src\DotNetCoreExtentions>cf curl /v2/info
{
   "name": "",
   "build": "",
   "support": "https://support.pivotal.io",
   "version": 0,
   "description": "",
   "authorization_endpoint": "https://login.system.apcf.io",
   "token_endpoint": "https://uaa.system.apcf.io",
   **"min_cli_version": "6.23.0",
   "min_recommended_cli_version": "6.23.0",
   "api_version": "2.75.0",**
   "app_ssh_endpoint": "ssh.system.apcf.io:2222",
   "app_ssh_host_key_fingerprint": "bd:9d:a0:69:05:3b:ab:96:f3:75:a0:3b:32:25:7d:ed",
   "app_ssh_oauth_client": "ssh-proxy",
   "routing_endpoint": "https://api.system.apcf.io/routing",
   "logging_endpoint": "wss://loggregator.system.apcf.io:4443",
   "doppler_logging_endpoint": "wss://doppler.system.apcf.io:4443",
   "user": "90e21abf-f8b6-4081-b204-1cfd2fec01a2"
}

CF CLI Version:
**cf version 6.24.0+c7a32d3.2017-02-10**

What version of the buildpack you are using?
I am **dotnet_core_buildpack**

If you were attempting to accomplish a task, what was it you were attempting to do?
I am deploying asp.net core webapi on pcf on linux cell and build pack is dotnet_core build pack

What did you expect to happen?
I am ubale to route to Index.html page -gettig 502 error after deploying application.If wetry to access app url.
I have also trie to put "api/xyzapi/2" next too root url still getting 502 error

What was the actual behavior?
**Application returns 502 Bad Gateway: Registered endpoint failed to handle the request.**

Please confirm where necessary:
* [done ] I have included a log output -attached log file
* [ ] My log includes an error message - not sure
* [ ] I have included steps for reproduction - when we tried to hit web api url it give 502 error
[AppLog.txt](https://github.com/cloudfoundry/dotnet-core-buildpack/files/1010412/AppLog.txt)

**Comment by sclevine** [comment]
Judging by your staging logs, it looks like your app is binding to port 5000, instead of port.
See: http://docs.cloudfoundry.org/buildpacks/dotnet-core/index.html#port

**Comment by sclevine** [comment]
Closing this for now. Let us know if you're still having issues.
