### ISSUE TITLE
v1.0.19 does not uninstall unused .NET core runtimes

### ISSUE THREAD

**Issue by mgoovaer** [cloudfoundry/dotnet-core-buildpack#150]
What version of Cloud Foundry and CF CLI are you using? (i.e. What is the output of running `cf curl /v2/info && cf version`?
cf version 6.23.0+c7866be18-2016-12-22

What version of the buildpack you are using?
v1.0.19 

If you were attempting to accomplish a task, what was it you were attempting to do?
cf push

What did you expect to happen?
Deploy the app ~220MB

What was the actual behavior?
Deploy the app ~377 MB
![buildpack 1 0 18](https://cloud.githubusercontent.com/assets/3597484/26353712/aaf15290-3f8f-11e7-9a46-45982a01a8d7.png)
![buildpack 1 0 19](https://cloud.githubusercontent.com/assets/3597484/26353713/aaf2105e-3f8f-11e7-8a01-002680daef15.png)

**Comment by sclevine** [comment]
I believe that this change was intentional, see #146.
