### ISSUE TITLE
Is there any plan to integrate the "dotnet-framework 2.0.0-preview2-25405-01" version

### ISSUE THREAD

**Issue by jagpreet86** [cloudfoundry/dotnet-core-buildpack#152]
What version of Cloud Foundry and CF CLI are you using? (i.e. What is the output of running `cf curl /v2/info && cf version`?

What version of the buildpack you are using?
dotnet core latest version

If you were attempting to accomplish a task, what was it you were attempting to do?
Trying to sample web api application based on .net core version "2.0.0-preview2-final'

What did you expect to happen?
It should load the specific version

What was the actual behavior? 
Error  :
       Downloading and installing .NET Core runtime 2.0.0-preview2-25407-01
       DEPENDENCY_MISSING_IN_MANIFEST: dotnet-framework.2.0.0-preview2-25407-01.
linux-amd64.tar.gz

Please confirm where necessary:
* [ ] I have included a log output
* [ ] My log includes an error message
* [ ] I have included steps for reproduction

**Comment by degrim** [comment]
@jagpreet86 The .NET Core 2.0-preview2 SDK is currently included in the develop branch and will be on the master branch with the next release.

**Comment by jagpreet86** [comment]
@degrim : Can I know the tentative plan/date for the next release ?

**Comment by sclevine** [comment]
Released: [v1.0.22](https://github.com/cloudfoundry/dotnet-core-buildpack/releases/tag/v1.0.22)

**Comment by jagpreet86** [comment]
@sclevine:  Released version to the dotnet framework buidpack is "2.0.0-preview2-25407-01" , but for hosting any service while using .NET Core 2.0 "2.0.0-preview2-25407-01" version . it expects assembly "Microsoft.AspNetCore.All" with version "2.0.0-preview2-final" which is not present in current build pack and thus getting below error.
Any immediate plans to move to "2.0.0-preview2-final" version ?

Error:
   2017-07-18T17:46:02.63+0530 [APP/PROC/WEB/0] ERR Error:
   2017-07-18T17:46:02.63+0530 [APP/PROC/WEB/0] ERR   An assembly specified in t
he application dependencies manifest (SampleWeb.deps.json) was not found:
   2017-07-18T17:46:02.63+0530 [APP/PROC/WEB/0] ERR     package: 'Microsoft.Appl
icationInsights.AspNetCore', version: '2.1.0-beta6'
   2017-07-18T17:46:02.63+0530 [APP/PROC/WEB/0] ERR     path: 'lib/netstandard1.
6/Microsoft.ApplicationInsights.AspNetCore.dll'
   2017-07-18T17:46:02.63+0530 [APP/PROC/WEB/0] ERR   This assembly was expected
 to be in the local runtime store as the application was published using the fol
lowing target manifest files:
   2017-07-18T17:46:02.63+0530 [APP/PROC/WEB/0] ERR     aspnetcore-store-2.0.0-p
review2-25794-linux-x64.xml;aspnetcore-store-2.0.0-preview2-25794-osx-x64.xml;as
pnetcore-store-2.0.0-preview2-25794-win7-x64.xml;aspnetcore-store-2.0.0-preview2
-25794-win7-x86.xml;aspnetcore-store-2.0.0-preview2-final-linux-x64.xml;aspnetco
re-store-2.0.0-preview2-final-osx-x64.xml;aspnetcore-store-2.0.0-preview2-final-
win7-x64.xml;aspnetcore-store-2.0.0-preview2-final-win7-x86.xml

**Comment by sclevine** [comment]
@dgodd @degrim thoughts on the above?
