### ISSUE TITLE
Failed to compile droplet for tibco bwce buildpack

### ISSUE THREAD

**Issue by shravanireddy16** [cloudfoundry/dotnet-core-buildpack#154]
Hi 
I am trying to upload my tibco application to PWS(Trial version) with the buildpack at GitHub:
https://github.com/shravanireddy16/Buildpack.git
And I get the below error. Can anyone please help me on this.

![pws_error](https://user-images.githubusercontent.com/30262674/28515476-6971079e-707b-11e7-9078-a10df5e11fc3.png)

**Comment by sclevine** [comment]
Hi @shravanireddy16,

This issue does not appear to be related to the .NET Core buildpack. Please reach out the maintainers of the TIBCO buildpack you are using for assistance.
