### ISSUE TITLE
regarding the support for Pivotal Cache

### ISSUE THREAD

**Issue by VenkateshSrini** [cloudfoundry/dotnet-core-buildpack#156]
Hi,
Regarding the support for Pivotal cloud cache, like Java application are you planning to provide it in build pack or will you provide the same as part of steel toe.

**Comment by sclevine** [comment]
Hi @VenkateshSrini,

Some information on this is [available here](https://discuss.pivotal.io/hc/en-us/community/posts/115007519728--NET-Core-GemFire-Native-Client-). I've reached out to the PCC team for more info.

**Comment by addisonhuddy** [comment]
Hi @VenkateshSrini, I'm working with a team at Pivotal to create a C# driver for Core & Framework that will work with Pivotal Cloud Cache.  Stay tuned.

**Comment by sclevine** [comment]
Thanks for the update @addisonhuddy. Closing this issue for now.

**Comment by VenkateshSrini** [comment]
@addisonhuddy,
Is there an GitHub url that I can subscribe to get to see the source code or get any updates in this regard

**Comment by addisonhuddy** [comment]
@VenkateshSrini Not at this time.

**Comment by VenkateshSrini** [comment]
So how do I get the updates

**Comment by addisonhuddy** [comment]
I recommend following Pivotal on Twitter. https://twitter.com/pivotal
