### ISSUE TITLE
DEPENDENCY_MISSING_IN_MANIFEST: dotnet-framework.1.0.1.linux-amd64.tar.gz -  .NET Core runtime version 1.0.1

### ISSUE THREAD

**Issue by ankgupta067** [cloudfoundry/dotnet-core-buildpack#157]
What version of Cloud Foundry and CF CLI are you using? (i.e. What is the output of running `cf curl /v2/info && cf version`?
cf version 6.22.2+a95e24c-2016-10-27

What version of the buildpack you are using?
using git url as buildpack

If you were attempting to accomplish a task, what was it you were attempting to do?
attempting to push an asp.net core 1.0.1 application 

What did you expect to happen?
Push to succeed

What was the actual behavior?
Following is the error on console 
BuildpackCompileFailed

in logs i see below error-

 [STG/0] [OUT] https://buildpacks.cloudfoundry.org/dependencies/dotnet/dotnet.1.0.4.linux-amd64-51ccea2c.tar.gz
 [STG/0] [OUT] Detected .NET Core runtime version 1.0.1 in /tmp/app/ServiceCatalog.runtimeconfig.json
 [STG/0] [OUT] Downloading and installing .NET Core runtime 1.0.1
 [STG/0] [OUT] OK
 [STG/0] [OUT] -----> Installing required .NET Core runtime(s)
 [STG/0] [OUT] FAILED: command failed, exit status 1
 [STG/0] [OUT] FAILED: Installing required .NET Core runtime(s) failed, command failed, exit status 1
 [STG/0] [OUT] DEPENDENCY_MISSING_IN_MANIFEST: dotnet-framework.1.0.1.linux-amd64.tar.gz

Please confirm where necessary:
* [ ] I have included a log output
* [ ] My log includes an error message
* [ ] I have included steps for reproduction

**Comment by degrim** [comment]
@ankgupta067 The current version of the buildpack does not support .NET Core 1.0.1.  Assuming you are using buildpack version 1.0.20 or higher, your application should be upgraded to 1.0.5 as that is the latest patch vesion for the 1.0 branch.

**Comment by ankgupta067** [comment]
@degrim thanks for your response, want to check if there is a possibility to get older version of builpacks, currently we refer buildpack by just giving url of git repository , how can i access older version of buildpack during cf push?

**Comment by degrim** [comment]
@ankgupta067 You can specify the release tag in the buildpack url like so:
`cf push <app_name> -b https://github.com/cloudfoundry/dotnet-core-buildpack.git#v1.0.19`

That would push with the v1.0.19 buildpack which still contains the 1.0.1 runtime.  However, I must warn you that there are **known security vulnerabilities** in that version of .NET Core and it is still recommended that you upgrade your application to using .NET Core 1.0.5.  Upgrading to the latest patch should not require any changes in your application other than specifying the new runtime version in your csproj or project.json file.

**Comment by ankgupta067** [comment]
@degrim  Thanks for your suggestion , i did update .net core version to 1.0.5 but after that i get a different error attaching error snapshot for your reference. following is my project.json now -
![error](https://user-images.githubusercontent.com/21137930/28770065-72376ff0-75fb-11e7-80b3-9afd5252a7e8.PNG)

{
  "version": "1.0.0-*",
  "buildOptions": {
    "emitEntryPoint": true
  },

  "dependencies": {
    "FhirNetCore": "17.2.6421.1204", ---- my custom package.
    "Microsoft.NETCore.App": "1.0.5"
  },

  "frameworks": {
    "netcoreapp1.0": {
      "imports": "dnxcore50"
    }
  },
  "runtimes": {"win10-x64": {}}
}

**Comment by degrim** [comment]
@ankgupta067 From your previous error message it looks like it was using the default SDK version (1.0.4) which is an MSBuild version.  You may need to specify the project.json SDK using a global.json file shown below:

```
{
  "sdk": {
    "version":"1.0.0-preview2-003156"
  }
}
```

**Comment by ankgupta067** [comment]
@degrim actualy that did not help but this entry helped -
 "Microsoft.NETCore.App": {
            "type": "platform",
            "version": "1.0.5"
        }
i am not sure why it worked after making this entry , project.json is very cryptic.

this is how now my project.json looks and latest build url without version works after migrating to 1.0.5

{
    "version": "1.0.0-*",
    "buildOptions": {
        "emitEntryPoint": true
    },

    "dependencies": {
        "FhirNetCore": "17.3.0.20",
        "Microsoft.NETCore.App": {
            "type": "platform",
            "version": "1.0.5"
        }
    },

    "frameworks": {
        "netcoreapp1.0": {
            "imports": "dnxcore50"
        }
    },
    "runtimes": {
        "win10-x64": {}
    }
}
and things work.
