### ISSUE TITLE
.NET Core 2.0 RTM

### ISSUE THREAD

**Issue by ReneHerrero** [cloudfoundry/dotnet-core-buildpack#159]
Hey guys,

Big news: .NET Core 2.0 got released today.  

I realize this is fresh off the press, just wanted to make sure you guys heard the news.  Can you provide an ETA?  

Thanks,

https://blogs.msdn.microsoft.com/dotnet/2017/08/14/announcing-net-core-2-0/

**Comment by mfjerome** [comment]
Definitly waiting for a .NET Core 2.0 RTM Buildpack!

**Comment by sclevine** [comment]
This is our highest priority item right now. Please see this epic:
https://www.pivotaltracker.com/epic/show/3708595

We expect .NET Core 2.0 (SDK+framework) to be available in the next release of the buildpack.

**Comment by nathan-alden** [comment]
I am definitely looking forward to this. Unfortunately, it seems that `dotnet new` can't create anything but .NET Core 2.0 projects so `cf push` fails with a million errors. I'm using `dotnet new` on Ubuntu with PCF Dev.

**Comment by sclevine** [comment]
Support for .NET Core 2.0 is available in v1.0.25. The 2.0 SDK is now the default SDK for C# and VB apps.

**Comment by degrim** [comment]
@nathan-alden You can also install the .NET Core 1.0 templates in the .NET Core 2.0 SDK by running `dotnet new -i Microsoft.DotNet.Web.ProjectTemplates.1.x::1.0.0-*` as Scott Hanselman described [here](https://www.hanselman.com/blog/ManagingDotnetCore20AndDotnetCore1xVersionedSDKsOnTheSameMachine.aspx).

Then the templates can be generated by specifying the framework to use like so:

`dotnet new mvc --framework netcoreapp1.1`
`dotnet new mvc --framework netcoreapp1.0`

This makes it a bit easier to use the new SDK with older frameworks.
