### ISSUE TITLE
.net core 2

### ISSUE THREAD

**Issue by andrecarlucci** [cloudfoundry/dotnet-core-buildpack#162]
Hi guys,
Any plans for .net core 2?
Tks!

**Comment by sclevine** [comment]
Hi @andrecarlucci,

Both the SDK and framework for .NET Core 2.0 are available in the latest release.

**Comment by andrecarlucci** [comment]
Thanks for the info, @sclevine , I asked because the Bluemix documentation is out of date.
I'll point my deploy to use the latest version directly from here.
Tks!
