### ISSUE TITLE
ERR Error: assembly specified in the dependencies manifest was not found

### ISSUE THREAD

**Issue by JayVictor** [cloudfoundry/dotnet-core-buildpack#167]
The below buildpacks doesn't seem to have all these DLL's?
dotnet_core_buildpack
dotnet_core_buildpack_2_0

ERR Error: assembly specified in the dependencies manifest was not found
 -- package: 'microsoft.extensions.localization.abstractions', version: '1.1.1', path: 'lib/netstandard1.0/Microsoft.Ext
ensions.Localization.Abstractions.dll'

 [APP/PROC/WEB/0] ERR Error: assembly specified in the dependencies manifest was not found
 -- package: 'nlog.extensions.logging', version: '1.0.0-rtm-beta5', path: 'lib/netstandard1.3/NLog.Extensions.Logging.dl
l'

 [APP/PROC/WEB/0] ERR Error: assembly specified in the dependencies manifest was not found
-- package: 'microsoft.visualstudio.web.codegeneration.entityframeworkcore', version: '1.1.1', path: 'lib/netstandard1.
/Microsoft.VisualStudio.Web.CodeGeneration.EntityFrameworkCore.dll'

**Comment by sclevine** [comment]
Hi @JayVictor,

Can you provide a sample app that demonstrates this behavior?

Also, are you sure that the `netstandard1` DLL you need is available in the .NET Core runtime for Linux version that you're using?

**Comment by JayVictor** [comment]
Hello sclevine,

Issue got fixed today morning.

While doing TFS Build and Release we are missing some dependencies. So i have added "build step" i.e. NuGet restore **/*.sln and it worked finally

Thanks!
