### ISSUE TITLE
Consider adding DOTNET_CLI_TELEMETRY_OPTOUT=1 environment variable to all cf_spec manifests

### ISSUE THREAD

**Issue by nathan-alden-inl** [cloudfoundry/dotnet-core-buildpack#169]
I've noticed some cf_specs in `manifest.yml` don't declare `DOTNET_CLI_TELEMETRY_OPTOUT=1`. Is this intentional? Due to security and legal considerations, I believe `DOTNET_CLI_TELEMETRY_OPTOUT` should be set to `1` in every .NET Core-related container.

**Comment by sclevine** [comment]
To clarify, are you suggesting that the buildpack set `DOTNET_CLI_TELEMETRY_OPTOUT=1`, or just that our sample apps do?

Are you worried about users who don't want their app reaching out to MS forgetting to set that, or are you worried about the integration tests reaching out to MS in all cases?

**Comment by sclevine** [comment]
Added to fixtures on `develop`.
