### ISSUE TITLE
C# 7.2 not supported with BuildPack 2.0.0

### ISSUE THREAD

**Issue by lunim** [cloudfoundry/dotnet-core-buildpack#176]
## What version of Cloud Foundry and CF CLI are you using? (i.e. What is the output of running `cf curl /v2/info && cf version`?
api version: 2.99.0
cf version: 6.34.0+f53d03a5e.2018-01-09

## What version of the buildpack you are using?
v2.0.0
URL: https://github.com/cloudfoundry/dotnet-core-buildpack.git#v2.0.0

## If you were attempting to accomplish a task, what was it you were attempting to do?
Deploy application using C# 7.2 language features, which is supported by .Net core Run-time 2.0.5.

Relevant csproj lines:

```
  <PropertyGroup>
    <TargetFramework>netcoreapp2.0</TargetFramework>
    <RuntimeFrameworkVersion>2.0.5</RuntimeFrameworkVersion>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <LangVersion>7.2</LangVersion>
  </PropertyGroup>
```

## What did you expect to happen?
Application deploys successfully

## What was the actual behavior?
Fails to deploy with error.  Tail of push log:

```
          Required dotnetframework versions: [2.0.5]
   -----> Installing dotnet-framework 2.0.5
          Download [https://buildpacks.cloudfoundry.org/dependencies/dotnet-framework/dotnet-framework.2.0.5.linux-amd64-62cc2fb0.tar.xz]
   -----> Publish dotnet
          Microsoft (R) Build Engine version 15.4.8.50001 for .NET Core
          Copyright (C) Microsoft Corporation. All rights reserved.

          CSC : error CS1617: Invalid option '7.2' for /langversion; must be ISO-1, ISO-2, Default, Latest or a valid version in range 1 to 7.1. [/tmp/app/TestCoreWebSDKApp.csproj]
   Exit status 223
          **ERROR** Unable to run dotnet publish: exit status 1
   Failed to compile droplet: Failed to run finalize script: exit status 12
```

**Comment by dgodd** [comment]
@lunim I am having trouble determining what MS versions of dotnet core support c# 7.2 . I can find references to Dotnet, but not core. Can you compile your app locally with dotnet-core 2.5?

**Comment by lunim** [comment]
@dgodd Support for 7.2 was added in the VS 15.5 version, which is part of the SDK 2.1.2 or later (https://github.com/dotnet/cli/releases/tag/v2.1.2), the latest version is 2.1.4.  It appears that the v2.0.0 buildpack is using SDK 2.0.3.

**Comment by dgodd** [comment]
Excellent @lunim . Do you want to close this issue? Or do you have extra suggestions to make this easier for users?

**Comment by lunim** [comment]
@dgodd I'll go ahead and close.  The main suggestion I have is to keep the default dotnet sdk set to the latest.  It took me a bit of searching to figure out how to manually specify my SDK version.

Thanks!
