### ISSUE TITLE
Is there any way to run .net core console application as long running-process?

### ISSUE THREAD

**Issue by Dennis-Petrov** [cloudfoundry/dotnet-core-buildpack#178]
What version of Cloud Foundry and CF CLI are you using? (i.e. What is the output of running `cf curl /v2/info && cf version`?
Assuming, that it's latest version.

What version of the buildpack you are using?
Assuming, that it's latest version (v2.0.1).

If you were attempting to accomplish a task, what was it you were attempting to do?
(none)

What did you expect to happen?
(none)

What was the actual behavior?
(none)

It's just a question, so, excuse me, if I've filled less info, than required.

I'm trying to understand, can I use Clound Foundry or not with my application, so, this question isn't version-specific (assuming, that latest version could be installed).

Buildpack [docs](https://docs.cloudfoundry.org/buildpacks/dotnet-core/index.html) means ASP .NET Core, but refers to "complete" .NET Core Framework page. Assuming, that, in fact, ASP .NET Core apps is started as console apps, is there any way to run .NET Core console application as long-running process, without instantiating web server? Where can I find the docs?

Thank you.

**Comment by sclevine** [comment]
You should be able to accomplish this by pushing the app without a healthcheck (`-u none`).

**Comment by Dennis-Petrov** [comment]
@sclevine, thanks, I'll try it. Are there any pitfalls/limitation in this case, comparing to ASP .NET web app?

**Comment by dgodd** [comment]
@Dennis-Petrov The problem with disabling the health check is that CF will no longer know if your app becomes unresponsive. CF will restart your app if it stops or if the health check fails, without the health check, restarts will only be triggered by your app stopping (not becoming unresponsive)

Depending on your use case this is probably OK, and depending on your other deployment alternatives, it is probably similar

**Comment by sclevine** [comment]
Closing as addressed.
