### ISSUE TITLE
Issue connecting to MS SQL Server running on non default port 1433

### ISSUE THREAD

**Issue by mahesji** [cloudfoundry/dotnet-core-buildpack#179]
What version of Cloud Foundry and CF CLI are you using? (i.e. What is the output of running `cf curl /v2/info && cf version`?

"api_version": "2.100.0"
cf version 6.23.0+c7866be-2016-12-22

What version of the buildpack you are using?
Dotnet-Core Buildpack version 2.0.2

If you were attempting to accomplish a task, what was it you were attempting to do?
Using System.Data.SqlClient to connect to Sql server database.  Following the sample in this post https://blogs.msdn.microsoft.com/dotnet/2016/11/09/net-core-data-access/ 

It works fine if the sql server is listening on port 1433 but fails when connecting to sql servers listening on port 1434. Confirmed that there is no network / firewall issues that that is blocking the ports. Able to connect to the same sql server on port 1434 using java / java buildpack within the same cf space. 
This connection string works > 
Server=myhostname,**1433**;Database=mydatabase;User Id=myuser;Password=mypassword;
This connection string does not work> 
Server=myhostname,**1434**;Database=mydatabase;User Id=myuser;Password=mypassword;

What did you expect to happen?
Successful connection to sql server

What was the actual behavior?
Connection fails with following error message 

_Record Fetch Error:  A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: TCP Provider, error: 35 - An internal exception was caught)_

Please confirm where necessary:
* [X ] I have included a log output
* [X ] My log includes an error message
* [X ] I have included steps for reproduction

**Comment by sclevine** [comment]
@dgodd May want to prioritize something to investigate.

@mahesji Do you observe the same behavior if you run your .NET Core app outside of CF? Can you provide us with a sample app that demonstrates this behavior?

**Comment by mahesji** [comment]
@sclevine Sorry, I should have closed this. I face this issue even if I run outside for CF.  Appears to be an issue with the core. Created this issue [https://github.com/dotnet/corefx/issues/27307](https://github.com/dotnet/corefx/issues/27307). Closing this one.  Thank you.
