### ISSUE TITLE
Execute Bash Commands at Run Time

### ISSUE THREAD

**Issue by fleming4** [cloudfoundry/dotnet-core-buildpack#180]
What version of Cloud Foundry and CF CLI are you using? (i.e. What is the output of running `cf curl /v2/info && cf version`?
cf version 6.34.0+f53d03a5e.2018-01-09

What version of the buildpack you are using?
dotnet_core_buildpack_1_0_33

If you were attempting to accomplish a task, what was it you were attempting to do?
Execute Bash Commands at run time

What did you expect to happen?
I expected the bash commands to execute

What was the actual behavior?
The Bash commands never run.

I am wanting to be able to run bash commands on the Cloud Foundry linux machine that is hosting my app. The bash command will be different based on what another service sends in via the api. 
Here is an example snippet of code that attempts to run a command using a bash shell:

Process proc = new Process
{
     StartInfo = new ProcessStartInfo
     {
           FileName = "/home/vcap/app/MyBash.sh",
           Arguments = "-c echo "Hello World",
           UseShellExecute = false,
           RedirectStandardOutput = false,
           CreateNoWindow = true
     }
};
proc.Start();
proc.WaitForExit();

Is doing something like this even possible?

**Comment by sclevine** [comment]
Can you provide a sample .NET Core app that you believe is misbehaving?

All Cloud Foundry apps are capable of executing additional processes, and bash is included in the rootfs.

**Comment by fleming4** [comment]
I was actually able to resolve the issue. My code was slightly wrong. I changed it to this and it works now:
Process proc = new Process
{
StartInfo = new ProcessStartInfo
{
FileName = "sh",
Arguments = "-c echo "Hello World",
UseShellExecute = true,
RedirectStandardOutput = false,
CreateNoWindow = true
}
};
proc.Start();
proc.WaitForExit();
