### ISSUE TITLE
Support for NET core 2.1 RC1

### ISSUE THREAD

**Issue by bartstinson** [cloudfoundry/dotnet-core-buildpack#182]
When will .NET Core 2.1 RC1 be supported?

**Comment by sclevine** [comment]
We have a policy of not including dependencies that are unsuitable for production use in the buildpack. However, we're considering making an exception here because Microsoft has indicated that 2.1 RC1 is suitable for production use, even though the versioning strongly suggests otherwise. I don't have an ETA for this yet.

**Comment by KyleCraviotto** [comment]
Would also love to see this as the 2.1 RC1 has many large performance improvements and Microsoft said we could go to Production with it 👍

**Comment by sclevine** [comment]
Scheduled for the next release, follow: https://www.pivotaltracker.com/story/show/157519453

**Comment by VenkateshSrini** [comment]
Eagerly waiting for this..

**Comment by mfjerome** [comment]
.NET Core 2.1 is now GA. https://blogs.msdn.microsoft.com/dotnet/2018/05/30/announcing-net-core-2-1/

**Comment by gornialberto** [comment]
Is there any ETA to get .NET Core 2.1  supported?  Even using the develop branch i see this error: 

-----> Dotnet-Core Buildpack version 2.0.6
-----> Supplying Dotnet Core
-----> Installing libunwind 1.2.1
       Copy [/tmp/cache/dependencies/10049b6ebf7e832b899ad805e311c53dfb50e6987726fb32743145262e3f3a74/libunwind-1.2.1-linux-x64-80af276a.tgz]
       using the default SDK
-----> Installing dotnet 2.1.300
       Download [https://buildpacks.cloudfoundry.org/dependencies/dotnet/dotnet.2.1.300.linux-amd64-07a2e2b2.tar.xz]
-----> Running go build finalize

       Version 2.1.0 of dependency dotnet-framework is not supported by this buildpack.
        - 1.0.11
        - 1.1.2
        - 1.1.7
        - 1.1.8
        - 2.0.0
        - 2.1.0-rc1-26423-06
       **ERROR** Unable to install required dotnet frameworks: dependency dotnet-framework 2.1.0 not found
-----> Finalizing Dotnet Core
       Required dotnetframework versions: [2.1.0]
-----> Installing dotnet-framework 2.1.0
       **ERROR** DEPENDENCY MISSING IN MANIFEST:
       The versions of dotnet-framework supported in this buildpack are:
        - 1.0.5
        - 1.0.10
        - 2.0.7
        - 2.1.0-rtm-26515-03

It sounds like ti downloads the right dependency dotnet.2.1.300 but then it fails in some place that i don't know!

**Comment by sclevine** [comment]
Apologies for the delay. We have a release scheduled will full support for 2.1 here:
https://www.pivotaltracker.com/story/show/157902665

**Comment by VenkateshSrini** [comment]
@sclevine ,
I did a quick scan of the issue, but I do not see an ETA. Could you please let us know when that is coming

**Comment by egilr** [comment]
Any news on version 2.1

-----> Running go build finalize
-----> Finalizing Dotnet Core
-----> Installing dotnet-framework 2.1.0
       **ERROR** DEPENDENCY MISSING IN MANIFEST:
       Version 2.1.0 of dependency dotnet-framework is not supported by this buildpack.
       The versions of dotnet-framework supported in this buildpack are:
        - 1.0.5
        - 1.0.10
        - 1.0.11
        - 1.1.2
        - 1.1.8
        - 2.0.0
        - 2.0.7

       **ERROR** Unable to install required dotnet frameworks: dependency dotnet-framework 2.1.0 not found
Failed to compile droplet: Failed to run finalize script: exit status 12
Stopping instance 16804373-2e93-4d99-a01b-37af71ebe680
Destroying container
       Required dotnetframework versions: [2.1.0]

        - 1.1.7
Exit status 223
Staging failed: STG: Exited with status 223

**Comment by sclevine** [comment]
This story is in-flight right now. We also have stories scheduled immediately after it that will make it easier to select the SDK and/or runtime with varying levels of specificity.

We have an unusually large number of buildpack-related requests right now. Apologies for the delay here. We're evaluating what changes we need to make to ship these releases faster.

**Comment by sclevine** [comment]
For some additional context, https://github.com/dotnet/cli/issues/9456 was causing issues, but we have a workaround for it now.

**Comment by sclevine** [comment]
.NET Core 2.1 SDKs and runtimes are available in the latest release.
