### ISSUE TITLE
JSON comments in runtimeconfig.json & deps.json causes buildpack parse failure

### ISSUE THREAD

**Issue by macsux** [cloudfoundry/dotnet-core-buildpack#185]
What version of Cloud Foundry and CF CLI are you using? (i.e. What is the output of running `cf curl /v2/info && cf version`?
cf version 6.25.0+787326d.2017-02-28
{
   "name": "",
   "build": "",
   "support": "https://support.run.pivotal.io",
   "version": 0,
   "description": "Cloud Foundry sponsored by Pivotal",
   "authorization_endpoint": "https://login.run.pivotal.io",
   "token_endpoint": "https://uaa.run.pivotal.io",
   "min_cli_version": "6.22.0",
   "min_recommended_cli_version": "latest",
   "api_version": "2.112.0",
   "app_ssh_endpoint": "ssh.run.pivotal.io:2222",
   "app_ssh_host_key_fingerprint": "e7:13:4e:32:ee:39:62:df:54:41:d7:f7:8b:b2:a7:6b",
   "app_ssh_oauth_client": "ssh-proxy",
   "doppler_logging_endpoint": "wss://doppler.run.pivotal.io:443",
   "routing_endpoint": "https://api.run.pivotal.io/routing",
   "user": "d0b5f4d4-a12a-42a1-a87e-15b8897bd009"
}

What version of the buildpack you are using?
2.0.6

If you were attempting to accomplish a task, what was it you were attempting to do?
Push application with a json comment inside runtimeconfig.json

What did you expect to happen?
App pushes successfully

What was the actual behavior?
Error:
Downloaded app package (45K)
-----> Dotnet-Core Buildpack version 2.0.6
-----> Supplying Dotnet Core
-----> Installing libunwind 1.2.1
       Copy [/tmp/buildpacks/1865cb8cb2c7c28910969490ce14f244/dependencies/35a6b4e9cad7a7fe8f8990e063509f7b/libunwind-1.2.1-linux-x64-80af276a.tgz]
       using the default SDK
-----> Installing dotnet 2.1.104
       Copy [/tmp/buildpacks/1865cb8cb2c7c28910969490ce14f244/dependencies/53a3ff6f58b4f9b410670a924cd2bb93/dotnet.2.1.104.linux-amd64-4c4036d4.tar.xz]
-----> Finalizing Dotnet Core
       **ERROR** Unable to install required dotnet frameworks: invalid character '/' after object key:value pair
Failed to compile droplet: Failed to run finalize script: exit status 12
Exit status 223

Please confirm where necessary:
* [X] I have included a log output
* [X] My log includes an error message
* [ ] I have included steps for reproduction

**Comment by sclevine** [comment]
Thanks for the report! Definitely seems like a  bug. We will prioritize this soon.

**Comment by ndon55555** [comment]
Closing as the fix for this has been applied
