### ISSUE TITLE
Missing git tag for realease v2.1

### ISSUE THREAD

**Issue by reto-ghioldi-foitt** [cloudfoundry/dotnet-core-buildpack#187]
We want to update to the new buildpack v2.1 (from version v2.0.7) and pin the version to a git tag.

Unfortunately there is no release/tag yet for version v2.1. Can you please create one? Thanks!

**Comment by sclevine** [comment]
We haven't cut an official release of this yet, and we're going to wait until #186 is evaluated before we do.

**Comment by sclevine** [comment]
Released.
