### ISSUE TITLE
ETA for .net core SDK 2.1.401 support

### ISSUE THREAD

**Issue by devindran** [cloudfoundry/dotnet-core-buildpack#194]
My organization is currently using buildpack v2.1.3 for dotnet core and we've been seeing one issue with running our applications on the cflinuxfs2 stack.

Any https calls made through a httpclient will fail with the following error
Exception":"System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception. ---> System.Security.Authentication.AuthenticationException: The remote certificate is invalid according to the validation procedure.

A valid workaround is to include the following bypass when setting up a httpclient
var httpClientHandler = new HttpClientHandler
            {
                ServerCertificateCustomValidationCallback = (message, cert, chain, errors) => true
            };

I was made to understand that Microsoft released a fix for this issue in their 2.1.401 SDK. Is there a timeline for when a buildpack that supports this SDK will be made available?

Thanks.

**Comment by sclevine** [comment]
This is already on the develop branch, which you can use directly with `-b https://github.com/cloudfoundry/dotnet-core-buildpack#develop`.

We plan to cut a release very soon, possibly today or tomorrow:
https://www.pivotaltracker.com/story/show/160141823

**Comment by devindran** [comment]
Thank you for your quick response. Will look forward to it.

**Comment by devindran** [comment]
Is there a revised timeline available for the new buildpack? I see the status is blocked.

**Comment by sclevine** [comment]
Apologies for the delay. We're making some changes to how the buildpack supplies ASP.NET Core assemblies for .NET Core 2.1. We could release it as-is, but there are some issues with FDD apps.

If the solution will take more than a few days to implement, we'll revert the ASP.NET Core work and cut a maintenance release. Either way, we plan to cut a release mid-week.

**Comment by devindran** [comment]
Thanks for the update

**Comment by ranjit-choudhury** [comment]
hi Stephen, do you know when can we get the new build packs for 2.4.1 ?

**Comment by sclevine** [comment]
Should be available later today or tomorrow.

**Comment by sclevine** [comment]
(assuming you mean a buildpack release with SDK 2.1.401)

**Comment by ranjit-choudhury** [comment]
> (assuming you mean a buildpack release with SDK 2.1.401)

Yes, sorry for the typo. Thanks for the quick response

**Comment by ranjit-choudhury** [comment]
hi ,
do we have any updated ETA for this ? We are blocked because of this and would really appreciate if we get a realistic date.

**Comment by sclevine** [comment]
Already released :)

**Comment by ranjit-choudhury** [comment]
Thanks Stephen for your quick response.
