### ISSUE TITLE
Graceful shutdown of application doesn't work properly

### ISSUE THREAD

**Issue by wormst** [cloudfoundry/dotnet-core-buildpack#195]
**What version of Cloud Foundry and CF CLI are you using?**
CF CLI version: 2.107.0
Cloud Foundry version: 6.37.0+a40009753.2018-05-25

**What version of the buildpack you are using?**
2.1.4 (https://github.com/cloudfoundry/dotnet-core-buildpack/releases/tag/v2.1.4)

**If you were attempting to accomplish a task, what was it you were attempting to do?**
I need to perform a clean-up on application shutdown (after cf stop, cf restart, cf delete or cf scale), but application does not retrieve SIGTERM signal properly.
It is ASP.NET Core application with dotnet-framework 2.1.2.

I'm trying to catch application shutdown in three ways (but non of them work properly), by attaching to these events:
1. IApplicationLifetime.ApplicationStopping
2. AppDomain.CurrentDomain.ProcessExit
3. AssemblyLoadContext.Default.Unloading

If I send SIGTERM manually when being inside container, all these methods are working properly.

**What did you expect to happen?**
Application to be killed gracefully.

**What was the actual behavior?**
Application wasn't killed gracefully.

**Comment by wormst** [comment]
It seems that I have found a workaround for this.

Normally, when the application is starting, it uses start command defined as following:
`start command: cd ${HOME} && dotnet ./Name.dll --server.urls http://0.0.0.0:${PORT}`

I have modified the start command by manually specifying it on cf push step (cf push -c "command") and modified the command itself by removing "cd" from the command like that:
`dotnet ${HOME}/Name.dll --server.urls http://0.0.0.0:${PORT}`

After that change application is being shutdown gracefully properly.

**Comment by aarro** [comment]
This lead me to Cloud Foundry's own documentation.

https://docs.cloudfoundry.org/devguide/deploy-apps/manifest-attributes.html#start-commands

Buried here, it describes how to make this work. I solved it by inserting `exec` into the default, like this:

`cd ${HOME} && exec ./serviceName --server.urls http://0.0.0.0:${PORT}`

Can this just be part of the dotnet buildpack's default? That's what I was using before, by virtue of leaving it out of my manifest. At the very least perhaps it should be more clearly listed in CF's docs? When trying to solve this issue before Google had lead me to the termination signal page here:

https://docs.cloudfoundry.org/devguide/deploy-apps/prepare-to-deploy.html#moving-apps

which describes how termination signals work in CF but doesn't offer this solution or a link to it.

**Comment by sclevine** [comment]
Seems like this was addressed shortly after the original report : https://github.com/cloudfoundry/dotnet-core-buildpack/commit/fdd56588e17442f39681b3c159965a0f1e44d36a https://github.com/cloudfoundry/dotnet-core-buildpack/commit/17ef9df959f1ded1c4dba7d7788ff189543b2ca5

Apologies for not closing the loop here sooner! Looks like the placeholder tracking issue was mistakenly closed too quickly.
