### ISSUE TITLE
Add Support For AppDynamics Monitoring

### ISSUE THREAD

**Issue by KyleCraviotto** [cloudfoundry/dotnet-core-buildpack#196]
I would expect to be able to use AppDynamics monitoring with the dotnet-core buildpack for PCF.
The blog post earlier in the year mentions capability will be added: https://blog.appdynamics.com/product/the-appd-approach-how-to-monitor-net-core-apps/

**Comment by pavankrish123** [comment]
@KyleCraviotto  Thanks for reaching out. We are going to release full fledged dotnet-core AppDynamics support through our extension buildpack, released as a part of our [AppDynamics Application Monitoring for PCF tile](https://network.pivotal.io/products/p-appdynamics/). 

We have already added support to HWC applications in our extension buildpack.

We expect the next release to have the support in our extension buildpack. (ETA this month). In the mean time please feel free to check the new workflow [documentation](https://docs.pivotal.io/partners/appdynamics/multibuildpack.html)

**Comment by pavankrish123** [comment]
@KyleCraviotto the support has been released in our latest tile. Kindly close this issue.
