### ISSUE TITLE
Getting buildpack error when trying to deploy a dotnet app

### ISSUE THREAD

**Issue by bamashah** [cloudfoundry/dotnet-core-buildpack#197]
What version of Cloud Foundry and CF CLI are you using? (i.e. What is the output of running `cf curl /v2/info && cf version`?

> {
>    "name": "Pivotal Application Service",
>    "build": "2.2.6-build.2",
>    "support": "https://support.pivotal.io",
>    "version": 0,
>    "description": "https://docs.pivotal.io/pivotalcf/2-2/pcf-release-notes/runtime-rn.html",
>    "authorization_endpoint": "https://login.system.c301.anadarko.io",
>    "token_endpoint": "https://uaa.system.c301.anadarko.io",
>    "min_cli_version": "6.23.0",
>    "min_recommended_cli_version": "6.23.0",
>    "api_version": "2.112.0",
>    "app_ssh_endpoint": "ssh.system.c301.anadarko.io:2222",
>    "app_ssh_host_key_fingerprint": "1d:15:06:72:e1:e1:11:f2:9b:92:61:66:1b:a0:4a:ca",
>    "app_ssh_oauth_client": "ssh-proxy",
>    "doppler_logging_endpoint": "wss://doppler.system.c301.anadarko.io:443",
>    "routing_endpoint": "https://api.system.c301.anadarko.io/routing",
>    "user": "10d6e589-2eb5-4c47-bdc2-2bc6032c7f23"
> }
> cf version 6.37.0+a40009753.2018-05-25

What version of the buildpack you are using?

https://github.com/cloudfoundry/dotnet-core-buildpack.git#v2.1.5

If you were attempting to accomplish a task, what was it you were attempting to do?

Attempting to deploy a dotnet app to PCF.

Is your dotnet app unpublished, platform-dependant, or self-contained?

It is configured to be self-contained

What did you expect to happen?

I expect the app to deploy, Mr Bond.

What was the actual behavior?

Did not deploy. Get this error:

> . . .
> . . .
>             Generating MSBuild file /tmp/app/test/unit/obj/AsapFlightAuthorization.UnitTest.csproj.nuget.g.props.
>             Generating MSBuild file /tmp/app/test/unit/obj/AsapFlightAuthorization.UnitTest.csproj.nuget.g.targets.
>             Restore completed in 2.61 sec for /tmp/app/test/unit/AsapFlightAuthorization.UnitTest.csproj.
>    Failed to compile droplet: Failed to run finalize script: exit status 12
>    Exit status 223
>    Cell a7ef8d59-aa1a-46eb-94a5-fa4bba1b8788 stopping instance 350bb35b-925e-4aa8-bd45-d96c107dc60e
>    Cell a7ef8d59-aa1a-46eb-94a5-fa4bba1b8788 destroying container for instance 350bb35b-925e-4aa8-bd45-d96c107dc60e
> Error staging application: App staging failed in the buildpack compile phase
> FAILED

Please confirm where necessary:
* [X] I have included a log output
* [X] My log includes an error message
* [ ] I have included steps for reproduction

**Comment by sclevine** [comment]
Could you provide all of the staging output and a sample version of the app that fails with the latest buildpack version?

It looks like the buildpack is trying to compile source code, which isn't necessary if you're pushing an SCD app.

**Comment by bamashah** [comment]
Thanks for the hint, Steve. I was not pushing the app from the output directory of the dotnet publish command. Did not know I needed to do that (not a .net guy and a pcf noob). Once I ran "cf push" from the publish output directory, it deployed fine.

**Comment by ljcorreia** [comment]
> Thanks for the hint, Steve. I was not pushing the app from the output directory of the dotnet publish command. Did not know I needed to do that (not a .net guy and a pcf noob). Once I ran "cf push" from the publish output directory, it deployed fine.

Thank you so much for pointing that out. It was also the issue for me the fact that the `cf push` needs to be called from the output directory of the `dotnet publish` command. It worth pointing out that in my case I am using the `cf cli` from a [Concourse Resource](https://freesoft.dev/program/84623051#cf-cli-concourse-resource), so the path parameter passed to the `cf cli` command needs to be the full path.

```yml
commands:
            - command: push
              path: my-repo/myapp
              manifest: my-repo/manifest.yml
```
