### ISSUE TITLE
Add Support for DevExpress Components

### ISSUE THREAD

**Issue by eddy-ooi** [cloudfoundry/dotnet-core-buildpack#198]
Please help to confirm DevExpress Reporting is supported in donet-core-buildpack.

https://community.devexpress.com/blogs/reporting/archive/2018/04/26/reporting-net-core-support-ctp-v18-1.aspx

**Comment by sclevine** [comment]
This appears to be distributed via NuGet, like other .NET Core packages. Are you running into issues with it? If so, can you provide a sample app that fails to stage/launch with those packages?

**Comment by tylerphelan** [comment]
Closing this out due to inactivity. Feel free to re-open if you continue having problems.
