### ISSUE TITLE
cflinuxfs2 depracated

### ISSUE THREAD

**Issue by mjnorman** [cloudfoundry/dotnet-core-buildpack#209]
Can you elaborate on the timeline of removing support for cflinuxfs2?  I see via the warning message that this is planned for April 2019.  Will there be a legacy version available for use in case upgrades are not completed by the time this happens?

```          
This application is being deployed on cflinuxfs2 which is being deprecated in April, 2019.
Please migrate this application to cflinuxfs3.
```

**Comment by shanks3012** [comment]
Canonical is ending support for Ubuntu 14.04 (cflimnuxfs2) at the end of April. From that point, cflinuxfs2 will not be able to receive patch updates for any known CVE's. While the timeline for removing the stack varies by foundation, it is highly recommended that you migrate your apps running cflinuxfs2 to cflinuxfs3 as soon as possible. We have a tool called stack-auditor which can assist in your migration to the new stack that you are welcome to use. See https://github.com/cloudfoundry/stack-auditor for more information around the tool.

The stack may stay around for a bit beyond the end of support, however it is best to expect that cflinuxfs2 will not stick around forever.

**Comment by sclevine** [comment]
We do plan to continue to release buildpacks for cflinuxfs2 after April to assist with the migration, and we don't yet have a timeline for removing cflinuxfs2 support from the buildpacks.

**Comment by dwillist** [comment]
Closing this issues as we have no hard dates for `cflinuxfs2` removal.
