### ISSUE TITLE
.NET Core 3.0 Preview

### ISSUE THREAD

**Issue by Tandis5** [cloudfoundry/dotnet-core-buildpack#210]
Are there any plans to add support for the preview version of .NET Core 3.0?

**Comment by dwillist** [comment]
We typically wait for an official release before including it in our buildpack. 

If you want to package your own buildpack with the .Net Core 3.0. You would need to alter your buildpacks [manifest.yml](https://github.com/cloudfoundry/dotnet-core-buildpack/blob/025e7c96d938bad24064cb700e29358d3bff5405/manifest.yml#L297) to include a  new entry for the 3.0 version. And then package up your buildpack using the [packager](https://github.com/cloudfoundry/libbuildpack/tree/master/packager)

**Comment by dwillist** [comment]
Opps, looks like we typically include a few preview versions! 

Will use be using the latter https://www.pivotaltracker.com/story/show/165612794.

Looks like we will be prioritizing this. Thanks!

**Comment by Tandis5** [comment]
Awesome!  Thank you!

**Comment by KyleCraviotto** [comment]
Now that preview7 is go-live will this preview be offered as a full release, or will it wait until there is an official release?

**Comment by ndon55555** [comment]
Hey @Tandis5 @KyleCraviotto, you can find .NET Core Preview 7 on our [latest](https://github.com/cloudfoundry/dotnet-core-buildpack/releases/tag/v2.2.13) release!
