### ISSUE TITLE
.NET Core version support policy not aligned with Microsoft's EOL policy?

### ISSUE THREAD

**Issue by john4242** [cloudfoundry/dotnet-core-buildpack#219]
I have just seen a message: "dotnet-runtime 2.2.x will no longer be available in new buildpacks released after 2019-12-23."
Digging a bit I realized this end of life date comes from Microsoft:
https://dotnet.microsoft.com/download/dotnet-core
And also: https://en.wikipedia.org/wiki/.NET_Core

My issue is that dotnet core 2.1.x seems to be an LTS version, but the cloud foundry buildpack doesn't consider this fact, it only supports the "last two major versions", which will be 3.0 only from late December?

In my opinion, the last LTS version should also be included in the buildpack, to help enterprises build complex systems with multiple modules and microservices in .net core.

**Comment by sclevine** [comment]
The policy is to include the last two **patch** versions and **all** supported version lines.
For example, 2.1 will not be dropped until it is EOL by Microsoft: https://github.com/cloudfoundry/dotnet-core-buildpack/blob/master/manifest.yml#L12
