### ISSUE TITLE
Support for .Net Core 3.1

### ISSUE THREAD

**Issue by pghtimwilson** [cloudfoundry/dotnet-core-buildpack#221]
With .Net Core 3.1 being released on 12/4/2019, it should be supported by the buildpack.

https://devblogs.microsoft.com/dotnet/announcing-net-core-3-1/

**Comment by Zanadar** [comment]
@pghtimwilson Thanks for the issue. This is now on develop and will ship with our next release (likely next week). https://github.com/cloudfoundry/dotnet-core-buildpack/compare/develop Going to close for now.

**Comment by shanks3012** [comment]
@pghtimwilson It may be a few weeks before this makes it to master due to a need to remove some older versions of the sdk and runtime. Just wanted to give you a heads up.

**Comment by Saloed123** [comment]
Wait)
