### ISSUE TITLE
Add .NET Core 3.1 to Buildpack

### ISSUE THREAD

**Issue by PicMan23** [cloudfoundry/dotnet-core-buildpack#223]

**Comment by ronnyek** [comment]
Already ran into a problem with lacking .netcore 3.0/3.1 support. Anxious to see this one resolved =)

**Comment by Saloed123** [comment]
Some news?

**Comment by Saloed123** [comment]
Need this ASAP

**Comment by cacodev** [comment]
Any update of when this is planned?

**Comment by mxplusb** [comment]
@sclevine would you or someone from your team be able to provide an update?

**Comment by jessecoddington-dsg** [comment]
"tomorrow" has came and gone yet still no buildpack.  Heroku released their buildpack a day after the 3.1 release.  Any reliable update?

**Comment by viz-morrell** [comment]
> "tomorrow" has came and gone yet still no buildpack. Heroku released their buildpack a day after the 3.1 release. Any reliable update?

3.1 has been the latest LTS for over a month.

This makes me very sad to have to wait this long...

**Comment by mxplusb** [comment]
> Any reliable update?

@jessecoddington-dsg `cf push -b https://github.com/cloudfoundry/dotnet-core-buildpack#develop` worked for me.

**Comment by jessecoddington-dsg** [comment]
Unfortunately we only support the release versions not development

**Comment by Chicopower** [comment]
Net Core 3.0 will reach end of support March 23 2020.
My team must update to Net Core 3.1 LTS ASAP.

Just release versions are usable here too.
Can someone help us with a reliable update?

**Comment by kvedurmu** [comment]
Hey folks - we just released [2.3.3](https://github.com/cloudfoundry/dotnet-core-buildpack/releases/tag/v2.3.3) which has 3.1. Apologies for the delays in getting this out!
