### ISSUE TITLE
AppDynamics for OSCF

### ISSUE THREAD

**Issue by mjnorman** [cloudfoundry/dotnet-core-buildpack#227]
Hi team.  I understand that there is an extension buildpack that has been released for PCF to enable AppDynamics support.  Is there a solution that can be used for sites that also host OSCF sites?  It may be as "simple" as extending the buildpack to add my own support for this, but was hoping that there was a more formal solution, since I am neither a buildpack developer or a Ruby aficionado.  Any advice?

**Comment by kvedurmu** [comment]
Hi. I don't believe there's an open source version of this extension buildpack. What you could do is customize the buildpack by adding an appdynamics profile script that sets up the agent (similar to https://github.com/cloudfoundry/nodejs-buildpack/blob/master/profile/appdynamics-setup.rb) and add the profile script to the [Buildpack manifest](https://github.com/cloudfoundry/nodejs-buildpack/blob/406c8dbaef2b167fb7e4cc59cdae272ead8e9e5e/manifest.yml#L21). I'm closing this issue for now, but feel free to reach out on slack or open this back up if you have any other questions.
