### ISSUE TITLE
Need the latest fix of libbuildpack-dynatrace module in the dotnet-core buildpack

### ISSUE THREAD

**Issue by manitheja1** [cloudfoundry/dotnet-core-buildpack#265]
Hi Team,
I could see the libbuildpack dynatrace module in the dotnet-core buildpack is using 1.2.2 version. There has been a latest release(1.3.0) for the module which has a fix to customize oneagenturl(https://github.com/Dynatrace/libbuildpack-dynatrace/releases ).

We need that fix in the dotnet-core buildpack. I know. could you please help us in getting the new release which will have the latest release of libbuildpack-dynatrace?

Thanks,
Manitheja

**Comment by kvedurmu** [comment]
This has been bumped and released in the latest version of the buildpack - https://github.com/cloudfoundry/dotnet-core-buildpack/releases/tag/v2.3.16
