### ISSUE TITLE
Allow using net5.0 as a framework name

### ISSUE THREAD

**Issue by ryanmoran** [cloudfoundry/dotnet-core-buildpack#300]
## Summary
Pushing a .NET5 app with the below entry in `.csproj` file results in the following error:

```
**ERROR** Unable to install dotnet-runtime: could not find a version of dotnet-runtime to install
```

The issue can be resolved by changing `TargetFramework` to the format as per .NET 3.x etc, "netcoreapp5.0"

According to Microsoft's list of monikers for target framework, shouldn't we support "net5.0"? https://docs.microsoft.com/en-us/dotnet/standard/frameworks

## Reproduction Steps

Sample app with project file:

`.csproj` file
```xml
<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net5.0</TargetFramework>
  </PropertyGroup>
</Project>
```

`buildpack.yml`
```yaml
dotnet-core:
  sdk: 5.x
```

Push the app and the above staging error is seen.

## Notes
Looks like the offending line of code may be here: https://github.com/cloudfoundry/dotnet-core-buildpack/blob/930ebd5f2eac7d4c64fd8c32108e6abc7b2d6ef6/src/dotnetcore/project/project.go#L343

**Comment by arjun024** [comment]
See similar issue in the Paketo project: https://github.com/paketo-buildpacks/dotnet-execute/issues/131

**Comment by kvedurmu** [comment]
Closing this. This has been fixed in https://github.com/cloudfoundry/dotnet-core-buildpack/releases/tag/v2.3.24

**Comment by fg-j** [comment]
Fixed in https://github.com/cloudfoundry/dotnet-core-buildpack/commit/2f221f6ef9e110ea188298c78d5b69549e55338f
