### ISSUE TITLE
Configuration issues when attempting to use dotnet tools to diagnose issues from the container

### ISSUE THREAD

**Issue by mjnorman** [cloudfoundry/dotnet-core-buildpack#313]
What version of Cloud Foundry and CF CLI are you using? (i.e. What is the output of running `cf curl /v2/info && cf version`?  
cf version 6.46.0+29d6257f1.2019-07-09

What version of the buildpack you are using?
latest - 2.3.22

If you were attempting to accomplish a task, what was it you were attempting to do?
install dotnet global tools, dotnet-trace, dotnet-dump, etc

Is your dotnet app unpublished, platform-dependant, or self-contained?
published 

What did you expect to happen?
tools should installation and run successfully

What was the actual behavior?
We are trying to troubleshoot some issues we are having with one of our apps.  In the course of troubleshooting, we are attempting to install global tools such as dotnet-trace and dotnet-dump.  There are a couple of issues that I see.  

1. `dotnet` is not on the PATH.  This means I have to fully qualify the path when running dotnet commands.  
2. upon installing the tool you are told that the tools directory is not on the path, which the tooling does give you a helpful output message to configure this, but it would be nice if this were already configured for ease of use.
3. upon running the tool you are told that the required library libhostfxr.so could not be found due to installation path configuration issues

```
~$dotnet-trace
A fatal error occurred. The required library libhostfxr.so could not be found.
If this is a self-contained application, that library should exist in [/home/vcap/.dotnet/tools/.store/dotnet-trace/5.0.160202/dotnet-trace/5.0.160202/tools/netcoreapp2.1/any/].
If this is a framework-dependent application, install the runtime in the global location [/usr/share/dotnet] or use the DOTNET_ROOT environment variable to specify the runtime location or register the runtime location in [/etc/dotnet/install_location].
```

setting the DOTNET_ROOT to the below allows the tool to work correctly 

```
export DOTNET_ROOT="/home/vcap/deps/0/dotnet-sdk"
```

**Comment by menehune23** [comment]
Hi @mjnorman, I'm closing this issue as stale. That said, if this is still an issue for you, please do reopen and we can look into it. If you reopen, please include a link to a minimal repo that reproduces the issue with detailed reproduction steps. Thanks!
