### ISSUE TITLE
NOTICE: [dotnet-core-buildpack] End of support for Node.js versions 10.x.x after 2021-05-27

### ISSUE THREAD

**Issue by shanks3012** [cloudfoundry/dotnet-core-buildpack#339]
The default version of Node.js in the .NET Core buildpack will change from the latest 10.x.x version to the latest 14.x.x version in the first release of the .NET Core buildpack after May 27, 2021. Due to the end of upstream support for Node.js 10.x.x, all buildpack users should ensure that their .NET Core apps run on a minimum buildpack supported version of Node.js 14.x.x or later.

Additionally, the .NET Core buildpack will temporarily include support for both Node.js versions 10.x.x and 14.x.x to allow .NET Core applications to build on 14.x.x prior to the removal of support for Node.js 10.x.x.

For more information about Node.js 10.x or LTS timelines for 10.x, refer to: https://github.com/nodejs/Release
For more information about supported Node.js versions in the .NET Core buildpack, refer to: https://buildpacks.cloudfoundry.org/#/buildpacks
 
Thanks,
Elliott Shanks, Buildpacks

**Comment by shanks3012** [comment]
Buildpacks Team - 

This issue represents the need to add support for Node.js 14.x in addition to the currently supported Node.js 10.x version line.

This will result in a .net-core buildpack that supports both Node.js 10.x as well as 14.x for the time being

**Comment by fg-j** [comment]
A version of the buildpack has been released adding node 14.x to the supported versions https://github.com/cloudfoundry/dotnet-core-buildpack/releases/tag/v2.3.27
