### ISSUE TITLE
Dates not being converted from UTC despite using Datetime.ToLocalTime or Datetime.IsDaylightSavingTime

### ISSUE THREAD

**Issue by Mark-Baxter** [cloudfoundry/dotnet-core-buildpack#382]
**What version of Cloud Foundry and CF CLI are you using? (i.e. What is the output of running `cf curl /v2/info && cf version`?**
{
 "name": "",
   "build": "",
   "support": "https://docs.cloud.service.gov.uk",
   "version": 0,
   "description": "",
   "authorization_endpoint": "https://login.london.cloud.service.gov.uk",
   "token_endpoint": "https://uaa.london.cloud.service.gov.uk",
   "min_cli_version": null,
   "min_recommended_cli_version": null,   
   "api_version": "2.166.0",
   "osbapi_version": "2.15",
   "user": "f8a12b65-4c1f-4752-8fc6-fb3f871deea2"
}
cf version 7.2.0+be4a5ce2b.2020-12-10

**What version of the buildpack you are using?**
Dotnet-Core Buildpack version 2.3.31
SDK 5.0.102

**If you were attempting to accomplish a task, what was it you were attempting to do?**
When we deploy a Blazor Server Side app the times are always returned as UTC. When we run it locally the time displays as the local time. See attached document
[UTC issues.docx](https://github.com/cloudfoundry/dotnet-core-buildpack/files/6733492/UTC.issues.docx)

**Is your dotnet app unpublished, platform-dependant, or self-contained?**
Platform dependent

**What did you expect to happen?**
When the Blazor Server Side app is deployed it displays datetimes in the local format

**What was the actual behavior?**
When the Blazor Server Side app is deployed it displays datetimes as UTC

**Comment by menehune23** [comment]
Hi @Mark-Baxter, thanks for posting. Is this still an issue? To help debug whether or not this is a problem with the buildpack, please reply with a link to minimal app that reproduces the problem, along with reproduction steps.

**Comment by Mark-Baxter** [comment]
Hi Andrew

We managed to resolve it by other methods.

All the best,
Mark.

**Comment by menehune23** [comment]
@Mark-Baxter thanks for the fast reply! I'll go ahead and close this then.
