### ISSUE TITLE
Deprecation notice required: [dotnet-core-buildpack] dotnet-runtime version 2.1.x***

### ISSUE THREAD

**Issue by cf-buildpacks-eng** [cloudfoundry/dotnet-core-buildpack#389]
Acceptance Criteria:

Confirm deprecation date is valid. If invalid, attempt to identify the best next opportunity to check for deprecation again. Modify the deprecation date on the buildpack with that new date.

Deprecation date: 2021-08-21
Link: https://dotnet.microsoft.com/platform/support/policy/dotnet-core

**Comment by bhh1893** [comment]
adressed here https://github.com/cloudfoundry/dotnet-core-buildpack/issues/404
