### ISSUE TITLE
IMPORTANT NOTICE: [dotnet-core-buildpack] End of Support for dotnet-runtime versions 2.1.x after 2021-08-21

### ISSUE THREAD

**Issue by bhh1893** [cloudfoundry/dotnet-core-buildpack#404]
The first release of the .NET Core buildpack after August 21, 2021 will no longer include dotnet-runtime versions 2.1.x. These .NET versions will no longer be supported upstream.[1] Please migrate your .NET Core apps to supported versions of dotnet-runtime before that time.

Note: Unless you are manually specifying a version of dotnet-runtime for the buildpack to use, or you have customized your .NET Core buildpack, no action is required.

As always, the buildpacks team is happy to answer questions you may have about this deprecation in the #buildpacks Slack channel.

[1] - https://dotnet.microsoft.com/platform/support/policy/dotnet-core

For more information on .NET Core dependencies and their deprecation dates, please refer to https://buildpacks.cloudfoundry.org/#/buildpacks

Thanks,
Buildpacks Team

**Comment by sophiewigmore** [comment]
Resolved by https://github.com/cloudfoundry/dotnet-core-buildpack/commit/f203e5aa6657db92a5a8d07e91c9879acbaa439b

**Comment by sophiewigmore** [comment]
It appears that there a lot of references to `2.1` in the buildpack code itself. We should also remove this before closing this issue out.
