### ISSUE TITLE
Use spec instead of ginkgo for testing

### ISSUE THREAD

**Issue by thitch97** [cloudfoundry/dotnet-core-buildpack#432]
# Background
Many of the integration tests in this repo are built around .NET Core v2.1.x dependencies, which has [recently reached End-of-Support status upstream](https://dotnet.microsoft.com/download/dotnet). We should ensure that our tests no longer rely on this version line before removing it from the buildpack. 

This provides an opportunity to begin using [spec](https://github.com/sclevine/spec) instead of ginkgo for our testing. 

We should rewrite the integration test suite in its entirety, using [this commit as an example](https://github.com/cloudfoundry/go-buildpack/commit/4ce1e15832e603d39a480a865b26456074ab038f).

As we audit each test, we should do the following:
1. Ask if the test still needs to be run, remove if no
2. Organize the test into a file where its alongside similar tests (like we do for CNBs)
3. Remove any fixtures that aren’t used
4. Organize the fixtures into logical groups
5. Modernize any of the fixtures that need it. **In particular, tests/fixtures which are pinned to a .NET Runtime, ASPNet Core or .NET SDK version within the 2.1.x line should be updated/rebuilt if still relevant.**

Blocks #404

**Comment by shanks3012** [comment]
Might run into some issues around CNB dotnet-execute cnb pertaining to node within. It may be worth seeing how this was resolved for the CNB in the event we run into similar issues on the v2b side.

**Comment by sophiewigmore** [comment]
Resolved by https://github.com/cloudfoundry/dotnet-core-buildpack/pull/445 merging to `develop`
