### ISSUE TITLE
IGNORE (testing): Deprecation: [dotnet-core-buildpack] dotnet-runtime version 3.1.x after 2021-10-04

### ISSUE THREAD

**Issue by sophiewigmore** [cloudfoundry/dotnet-core-buildpack#453]
The dotnet-runtime 3.1.x dependency is scheduled to be deprecated on: 2021-10-04.

Confirm this deprecation date is valid, and do one of the following:
- [ ] If the deprecation date is valid, check this box. Keep this issue open and remove the version line on or after the given deprecation date.
- [ ] If the deprecation date is **not** valid, please update it accordingly in the [dependency-builds](https://github.com/cloudfoundry/buildpacks-ci/blob/master/pipelines/config/dependency-builds.yml) configuration, and close this issue with a link to the commit.

See the following documentation for more information: https://dotnet.microsoft.com/platform/support/policy/dotnet-core

**Comment by robdimsdale** [comment]
Ignore this - it's a test. Closing.
