### ISSUE TITLE
Source-based apps should have an SDK intelligently installed

### ISSUE THREAD

**Issue by menehune23** [cloudfoundry/dotnet-core-buildpack#460]
When staging source-based apps that use a non-default version of the SDK, this buildpack should lookup which SDK to install based on the contents of `*.csproj`, removing the requirement to use a `buildpack.yml` or `global.json` to specify the SDK.

We do part of this during finalize, where we [parse the runtime version from the project](https://github.com/cloudfoundry/dotnet-core-buildpack/blob/26d296182f3a972c3a9c910da095647500dba410/src/dotnetcore/finalize/finalize.go#L63).

We could extract that version-gathering logic into a DRYer location and combine it with the [runtime->SDK mapping](https://github.com/cloudfoundry/dotnet-core-buildpack/blob/master/manifest.yml#L164) that we maintain in our manifest to go from `*.csproj` -> `<runtime version>` -> `<SDK version>` and install that.

Here's an example of [BRATs using the mapping info to build a go map](https://github.com/cloudfoundry/dotnet-core-buildpack/blob/26d296182f3a972c3a9c910da095647500dba410/src/dotnetcore/brats/brats_suite_test.go#L144).

Open questions:
- What about `*.fsproj` and `*.vbproj`? It seems our buildpack might already handle this (see [here](https://github.com/cloudfoundry/dotnet-core-buildpack/blob/26d296182f3a972c3a9c910da095647500dba410/src/dotnetcore/project/project.go#L232) and [here](https://github.com/cloudfoundry/dotnet-core-buildpack/blob/26d296182f3a972c3a9c910da095647500dba410/src/dotnetcore/project/project.go#L186)) without extra code.

Relates to #446

**Comment by johnnyr0x** [comment]
@sophiewigmore @ForestEckhardt - please review and close if applicable.

**Comment by ForestEckhardt** [comment]
I think that I agree with @macsux assessment of the situation. Also that mapping has been removed.
