### ISSUE TITLE
.NET buildpack should default to latest SDK (6.x)

### ISSUE THREAD

**Issue by macsux** [cloudfoundry/dotnet-core-buildpack#517]
With introduction of .NET 6 LTS, there's no reason to default to 3.1 as the default SDK. .NET SDKs are designed to be backwards compatible and it is expected that the latest one is used by default unless explicitly overridden. The behavior of the buildpack is not consistent with how things work, and in fact it's using 3.1 SDK to publish 6.x apps which has a much higher likelihood of creating incorrect result then by using v6.x SDK to publish 3.1 apps.

**Comment by brayanhenao** [comment]
We will put this issue in our backlog for further investigation of possible compatibility issues when changing the default version to 6.x.

**Comment by brayanhenao** [comment]
@macsux .NET Core Buildpack [v2.3.43](https://github.com/cloudfoundry/dotnet-core-buildpack/releases/tag/v2.3.43) released with the changes mentioned above
