### ISSUE TITLE
Error with libunwind on PCF push

### ISSUE THREAD

**Issue by jbogenschneider** [cloudfoundry/dotnet-core-buildpack#58]
[TestCore.zip](https://github.com/cloudfoundry-community/dotnet-core-buildpack/files/305019/TestCore.zip)

I did a ubuntu 14.4 self contained (to the best of my knowledge) build with RC2 and get this error from cli client when pushing to PCF. I get it from Linux cli and Mac

mkeloxmr45gfd57:BuildPackTest xxxxxxx$ cf push dotnettestapi -b https://github.com/cloudfoundry-community/dotnet-core-buildpack.git
Updating app dotnettestapi in org xxxxxx / space sb as xxxxxxx...
OK

Uploading dotnettestapi...
Uploading app files from: /users/xxxxx/documents/docker/BuildPackTest
Uploading 49.9M, 180 files
Done uploading

OK

Starting app dotnettestapi in org .......
Creating container
Successfully created container
Downloading app package...
Downloaded app package (20.6M)
Staging...
ASP.NET Core buildpack version: 0.8.0
ASP.NET Core buildpack starting compile
-----> Restoring files from buildpack cache
OK
-----> Extracting libunwind
libunwind version: 1.1
/usr/lib/ruby/2.2.0/digest.rb:49:in initialize': No such file or directory @ rb_sysopen - /tmp/libunwind-x-1.1.tar.gz (Errno::ENOENT) from /usr/lib/ruby/2.2.0/digest.rb:49:inopen'
from /usr/lib/ruby/2.2.0/digest.rb:49:in file' from /usr/lib/ruby/2.2.0/digest.rb:34:infile'
from /tmp/buildpacks/63d5a1e25de8205658beee5d2f0c1aa0/compile-extensions/bin/download_dependency:30:in `

'
FAILED: command failed, exit status 1
FAILED: Extracting libunwind failed, command failed, exit status 1
Failed to compile droplet
Exit status 223
Staging failed: Exited with status 223
FAILED
BuildpackCompileFailed

**Comment by degrim** [comment]
There's a piece missing from your project.json file to make it publish the app as self-contained in a format that the buildpack will recognize:

      "buildOptions": {
        "emitEntryPoint": true
      },

You're also missing the following line, which should be at line 24 in your `Program.cs` file:

    .UseConfiguration(config)

After adding that I'm able to push to CF, so this might be an issue specific to PCF.

**Comment by jbogenschneider** [comment]
Thanks, I made those changes, which will help me once I get past this issue.  I'll try and push with a locally modified version of this buildpack, removing or loading that lib a different way.  Won't be able to do it today though.

**Comment by jbogenschneider** [comment]
so dependencies in the yaml has:
dependencies:
  - name: libunwind
    version: 1.1
    cf_stacks:
      - cflinuxfs2
    uri: https://github.com/cloudfoundry-community/asp.net5-buildpack/releases/download/v0.7/libunwind-cflinuxfs2-1.1.tar.gz
    md5: b76452a8a2400f3cfdf189761e8be97e

but the error I see on my push says "No such file" for /tmp/libunwind-x-1.1.tar.gz  
If PCF is causing it within the digest to use the wrong name (the one from the savanah download) then I can talk to Pivotal, but do you think it could work by changing the URI in the yaml?

**Comment by opiethehokie** [comment]
The relevant code is in https://github.com/cloudfoundry/compile-extensions/blob/4a0e48afc46c1d467b7c75a8ae5e6f3a044d3d64/bin/download_dependency

The curl command on line 29 must be failing for you. It would create the file /tmp/libunwind-x-1.1.tar.gz. The only way I've been able to recreate this is by changing the hostname in manifest.yml from github.com to something that doesn't exist. It seems like the https://github.com/cloudfoundry-community/asp.net5-buildpack/releases/download/v0.7/libunwind-cflinuxfs2-1.1.tar.gz dependency is unreachable.

**Comment by jbogenschneider** [comment]
so I'm new to this and I can confirm with our DevOps but as you indicate the libunwind is probably not downloading due to network, so I know from the "pull request" that there is a request for a cached buildpack which would include libunwind?

**Comment by degrim** [comment]
That pull request was referencing a different dependency, the framework is already in place to enable caching of libunwind.

**Comment by janaka** [comment]
I also get this error on a OSX when I down load the 0.8 zip file, cf create-buildpack > cf push.

When I run 

`cf push pingpong_api -b https://github.com/cloudfoundry-community/asp.net5-buildpack.git`

it works fine.

**Comment by opiethehokie** [comment]
The releases include a "cached" buildpack zip now, so that path is easier now. I think we can close this. See https://github.com/cloudfoundry/dotnet-core-buildpack/releases/tag/v1.0.2.
