### ISSUE TITLE
Release: dotnet-core-buildpack (Mar)

### ISSUE THREAD

**Issue by cf-buildpacks-eng** [cloudfoundry/dotnet-core-buildpack#752]
Release reminder for dotnet-core-buildpack

* See [diff from latest version](https://github.com/cloudfoundry/dotnet-core-buildpack/compare/v2.4.8..develop) and validate if a release is required.
* Make sure the latest commit on  has passed tests on the [CI](https://buildpacks.ci.cf-app.com/teams/main/pipelines/dotnet-core-buildpack)
* Refer [release instructions](https://github.com/pivotal-cf/tanzu-buildpacks/wiki/Releasing-CF-Buildpacks). (private link)

**Comment by ForestEckhardt** [comment]
This was just release (https://github.com/cloudfoundry/dotnet-core-buildpack/releases/tag/v2.4.8)
