### ISSUE TITLE
Release: dotnet-core-buildpack (Feb)

### ISSUE THREAD

**Issue by cf-buildpacks-eng** [cloudfoundry/dotnet-core-buildpack#906]
Release reminder for dotnet-core-buildpack

* See [diff from latest version](https://github.com/cloudfoundry/dotnet-core-buildpack/compare/v2.4.21..develop) and validate if a release is required.
* Make sure the latest commit on  has passed tests on the [CI](https://buildpacks.ci.cf-app.com/teams/main/pipelines/dotnet-core-buildpack)
* Refer [release instructions](https://github.com/pivotal-cf/tanzu-buildpacks/wiki/Releasing-CF-Buildpacks). (private link)

**Comment by arjun024** [comment]
Consider upgrading default version to .NET 6. See [private slack link](https://vmware.slack.com/archives/CUR2H2KFE/p1707929193296109)

**Comment by ForestEckhardt** [comment]
https://github.com/cloudfoundry/dotnet-core-buildpack/releases/tag/v2.4.23
