### ISSUE TITLE
.net core app failed to start

### ISSUE THREAD

**Issue by emailtowalter** [cloudfoundry/dotnet-core-buildpack#94]
Hi there... When I deploy my asp.net core app on bluemix, it failed to start with return code -1. But it runs ok on my win7 dev machine.  I am looking for suggestion on how to debug the issue. 

So far, I have done the following steps , but still cannot find the issue. 
-- add cf push myapp -c:"sleep 5;dotnet run --project:myproject --server.urls:0.0.0.0:{port}"
-- enable CF CLI json call trace by setting enviroment variable cf_trace=ture. 

Thanks, 

Walter

**Comment by emailtowalter** [comment]
I found the issue which is odd. I have a testing project using xunit. I found the project is  netcoreapp1.0 , meaning it is a app. After removing it, thing goes back to normal. It begs 2 questions: 1. I do not have the same issue when run the site locally from solution folder. why does it fail ? 2. thought the .deployment file specify which project is to launch. 

thought? 

"frameworks": {
    "netcoreapp1.0": {
      "dependencies": {
        "Microsoft.NETCore.App": {
          "type": "platform",
          "version": "1.0.0"
        }
      },
      "imports": [
        "dotnet5.4",
        "portable-net451+win8"
      ]
    }

**Comment by degrim** [comment]
That does seem strange that the test project would cause the deployment to fail, it shouldn't even be compiled when the .deployment file specifies a project which does not depend on it.

**Comment by degrim** [comment]
@emailtowalter Were you pushing the app from source, or from a published app folder?  What disk quota were you using for the app?

**Comment by emailtowalter** [comment]
C push from solution folder. Here is the structure:
Solution
solution\src
solution\test

I ram and disk quota I 1g.

**Comment by RochesterinNYC** [comment]
@emailtowalter Is this still a problem?

Can you provide some more log output or a sample app to reproduce? Thanks.

**Comment by emailtowalter** [comment]
I believe the issue is still there. But busy with prod implementation on bluemix. Will do that when I have some cycle. Thanks

**Comment by degrim** [comment]
@emailtowalter I have seen some cases where the deployment fails because the app takes more than 1g disk space, resulting in a -1 exit code when the app is terminated for exceeding the quota for disk space.

@RochesterinNYC Once the msbuild changes are made, apps shouldn't be taking nearly as much disk space as published applications are much smaller.

**Comment by sesmith177** [comment]
@emailtowalter is this still an issue for you / have you had time to work on this?

Thanks.

**Comment by RochesterinNYC** [comment]
@emailtowalter closing this issue due to lack of response. If it's still a concern, please let us know.

**Comment by emailtowalter** [comment]
‎Fair. Just kinda busy to implement fist. NET Core on CF in prod.                                                                                                                                                                                                                                                                                                                                         Sent from my BlackBerry 10 smartphone on the Rogers network.                                                                                                                                                                                                                From: James WenSent: Thursday, December 1, 2016 12:21 PMTo: cloudfoundry/dotnet-core-buildpackReply To: cloudfoundry/dotnet-core-buildpackCc: emailtowalter; MentionSubject: Re: [cloudfoundry/dotnet-core-buildpack] .net core app failed to start (#94)@emailtowalter closing this issue due to lack of response. If it's still a concern, please let us know.

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/cloudfoundry/dotnet-core-buildpack","title":"cloudfoundry/dotnet-core-buildpack","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/cloudfoundry/dotnet-core-buildpack"}},"updates":{"snippets":[{"icon":"PERSON","message":"@RochesterinNYC in #94: @emailtowalter closing this issue due to lack of response. If it's still a concern, please let us know."}],"action":{"name":"View Issue","url":"https://github.com/cloudfoundry/dotnet-core-buildpack/issues/94#issuecomment-264235754"}}}
