### ISSUE TITLE
Could we update the default .NET sdk version to 8.0.*

### ISSUE THREAD

**Issue by Piimawi** [cloudfoundry/dotnet-core-buildpack#951]
While the development of a .NET app for SAP BTP (cflinux4) I have seen that the default SDK version is .NET 6.0.*
Is there a special reason for that?
I have tried out 8.0.* and on the first look it seems to work (only tested with a simple Blazor app): https://github.com/Piimawi/dotnet-core-buildpack/blob/master/manifest.yml.

This would be the latest long term sdk version I think: https://dotnet.microsoft.com/en-us/download/dotnet

**Comment by sophiewigmore** [comment]
this was done in https://github.com/cloudfoundry/dotnet-core-buildpack/releases/tag/v2.4.27
